USE [Sistema Gestao]
GO
/****** Object:  StoredProcedure [dbo].[STP_SelecionaEmpresaPorFiltro]    Script Date: 03/25/2011 17:41:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[STP_SelecionaEmpresaPorFiltro]
(
	@CEA_TURMA INT,  
	@CEA_ESTADO INT,  
	@CEA_ESCRITORIO_REGIONAL INT,  
	@CEA_ESTADO_REGIAO INT,  
	@CEA_CIDADE INT,  
	@CEA_FATURAMENTO INT,  
	@NU_FUNCIONARIOS INT,  
	@CEA_NIVEL_ESCOLARIDADE INT,  
	@CEA_FAIXA_ETARIA INT,  
	@sNOME_FANTASIA VARCHAR(500),  
	@sRAZAO_SOCIAL VARCHAR(500),  
	@CPF_CNPJ VARCHAR(200),  
	@STATUS INT,  
	@CEA_CATEGORIA INT,  
	@TIPO_EMPRESA INT,  
	@TX_SEXO_CONTATO CHAR(1),  
	@CEA_GRUPO INT,  
	@PROTOCOLO VARCHAR(200),  
	@DATAINICIO DATETIME,  
	@DATAFIM DATETIME,  
	@FL_PARTICIPA_PROGRAMA BIT,
	@CEA_TIPO_ETAPA INT
)
As    
BEGIN     
SET NOCOUNT ON  

	 SELECT DISTINCT   
		--TBL_EMP_CADASTRO   
		TE.CEA_EMP_CADASTRO  
		,E.TX_RAZAO_SOCIAL  
        ,E.TX_NOME_FANTASIA  
        ,E.TX_CPF_CNPJ
        --TBL_ESTADO  
        --,ES.CDA_ESTADO  
        ,ETA.FL_ATIVO AS FL_ETAPA_ATIVA
        ,ES.TX_ESTADO
        ,E.DT_ABERTURA_EMPRESA  
        ,E.FL_PARTICIPOU_MPE_2006  
        ,E.FL_PARTICIPOU_MPE_2007  
        ,E.FL_PARTICIPOU_MPE_2008  
        ,E.FL_PARTICIPOU_MPE_2009  
        ,E.FL_PARTICIPOU_MPE_2010  
        ,E.FL_PARTICIPOU_MPE_2011  
        ,TE.FL_PARTICIPA_PROGRAMA  
        ,TE.CEA_TURMA  
        -----------------------  
        --TBL_TURMA_EMP  
        ,TE.NU_FUNCIONARIO  
        ,TE.TX_ENDERECO  
        ,TE.TX_COMPLEMENTO  
        ,TE.FL_ATIVO  
        ,TE.DT_ULTIMA_ALTERACAO  
        ,TE.CEA_PAIS  
        ,TE.TX_CEP  
        ,TE.CEA_TURMA  
        ,TE.CEA_USUARIO  
        ,TE.FL_PARTICIPA_PROGRAMA
        ,TE.TX_NOME_CONTATO  
        ,TE.TX_ENDERECO_CONTATO  
        ,TE.TX_TELEFONE_CONTATO  
        ,TE.TX_CELULAR_CONTATO  
        ,TE.TX_EMAIL_CONTATO  
        ,TE.DT_DATA_NASCIMENTO_CONTATO  
        ,TE.TX_SEXO_CONTATO  
        ,TE.TX_MENSAGEM_CONTATO  
        ,TE.TX_CPF_CONTATO  
        ,TE.FL_PERGUNTA1  
        ,TE.FL_PERGUNTA2  
        ,TE.FL_PERGUNTA3  
        ,TE.FL_PERGUNTA4  
        ,TE.DT_CADASTRO  
        ,TE.TX_CEP_CONTATO  
        ,TE.CEA_ESTADO_CONTATO  
        ,TE.CEA_CIDADE_CONTATO  
        ,TE.CEA_BAIRRO_CONTATO  
        ,TE.CEA_ESTADO
        ------------------------  
        --TBL_CIDADE  
        ,TE.CEA_CIDADE  
        ,CI.TX_CIDADE  
        ------------------------  
  
        --------------------------  
        ----TBL_TIPO_EMP  
        ,TE.CEA_TIPO_EMPRESA  
        ,TI.TX_TIPO_EMPRESA  
        ------------------------  
        ----TBL_FATURAMENTO  
        ,TE.CEA_FATURAMENTO  
        ,FA.TX_FATURAMENTO  
        ------------------------  
        ----TBL_CATEGORIA  
        ,TE.CEA_CATEGORIA  
        ,CAT.TX_CATEGORIA  
        ------------------------  
        ----TBL_AITIVIDADE_ECONOMICA  
        ,TE.CEA_ATIVIDADE_ECONOMICA  
        ,TE.TX_ATIVIDADE_ECONOMICA 
        ,AE.TX_ATIVIDADE_ECONOMICA AS TX_ATIVIDADE_ECONOMICA_PRINCIPAL
        ----------------------  
        --TBL_BAIRRO  
        ,TE.CEA_BAIRRO  
        ,BA.TX_BAIRRO  
        ------------------------  
        --TBL_CARGO  
        ,TE.CEA_CARGO  
        ,CA.TX_CARGO  
        ------------------------  
        --TBL_CONTATO_NIVEL_ESCOLARIDADE  
        ,TE.CEA_NIVEL_ESCOLARIDADE  
        ,NE.TX_NIVEL_ESCOLARIDADE  
        ------------------------  
        --TBL_CONTATO_FAIXA_ETARIA  
        ,TE.CEA_FAIXA_ETARIA  
        ,FE.TX_FAIXA_ETARIA
        
         --TBL_CIDADE  CONTATO 
         ,CIC.TX_CIDADE CIDADE_CONTATO
         --TBL_ESTADO  CONTATO
         ,ESC.TX_SIGLA ESTADO_CONTATO
         --TBL_BAIRRO  CONTATO
         ,BAC.TX_BAIRRO BAIRRO_CONTATO
FROM TBL_EMP_CADASTRO E  
		JOIN TBL_TURMA_EMP TE ON TE.CEA_EMP_CADASTRO = E.CDA_EMP_CADASTRO 
		JOIN TBL_ETAPA ETA ON ETA.CEA_TURMA = TE.CEA_TURMA AND ETA.CEA_ESTADO = TE.CEA_ESTADO AND ETA.CEA_TIPO_ETAPA = @CEA_TIPO_ETAPA
		INNER JOIN TBL_QUESTIONARIO_EMPRESA QE ON QE.CEA_EMP_CADASTRO = TE.CEA_EMP_CADASTRO
		INNER JOIN TBL_ETAPA ETTEMP ON ETTEMP.CDA_ETAPA = QE.CEA_ETAPA
		JOIN TBL_BAIRRO BA ON BA.CDA_BAIRRO = TE.CEA_BAIRRO  
		JOIN TBL_CIDADE CI ON CI.CDA_CIDADE = TE.CEA_CIDADE  
		JOIN TBL_ESTADO ES ON ES.CDA_ESTADO = TE.CEA_ESTADO  
		JOIN TBL_BAIRRO BAC ON BAC.CDA_BAIRRO = TE.CEA_BAIRRO_CONTATO  
		JOIN TBL_CIDADE CIC ON CIC.CDA_CIDADE = TE.CEA_CIDADE_CONTATO
		JOIN TBL_ESTADO ESC ON ESC.CDA_ESTADO = TE.CEA_ESTADO_CONTATO
		LEFT JOIN TBL_REL_CIDADE_ESCRITORIO_REGIONAL trcer ON trcer.CEA_CIDADE = CI.CDA_CIDADE  
		LEFT JOIN TBL_ESCRITORIO_REGIONAL ter ON ter.CDA_ESCRITORIO_REGIONAL = trcer.CEA_ESCRITORIO_REGIONAL AND ter.CEA_TURMA = te.CEA_TURMA  
		JOIN TBL_CARGO CA ON CA.CDA_CARGO = TE.CEA_CARGO          
		JOIN TBL_TIPO_EMP TI ON TI.CDA_TIPO_EMPRESA = TE.CEA_TIPO_EMPRESA  
		JOIN TBL_FATURAMENTO FA ON FA.CDA_FATURAMENTO = TE.CEA_FATURAMENTO  
		JOIN TBL_CATEGORIA CAT ON CAT.CDA_CATEGORIA = TE.CEA_CATEGORIA  
		JOIN TBL_ATIVIDADE_ECONOMICA AE ON AE.CDA_ATIVIDADE_ECONOMICA = TE.CEA_ATIVIDADE_ECONOMICA  
		JOIN TBL_CONTATO_NIVEL_ESCOLARIDADE NE ON NE.CDA_NIVEL_ESCOLARIDADE = TE.CEA_NIVEL_ESCOLARIDADE  
		JOIN TBL_CONTATO_FAIXA_ETARIA FE ON FE.CDA_FAIXA_ETARIA = TE.CEA_FAIXA_ETARIA  
		LEFT JOIN TBL_GRUPOEMPRESA GE ON GE.CEA_EMP_CADASTRO = E.CDA_EMP_CADASTRO  
		LEFT JOIN TBL_ESTADO_REGIAO ter2 ON ter2.CDA_ESTADO_REGIAO = CI.CEA_ESTADO_REGIAO   
WHERE E.TX_NOME_FANTASIA like '%' + @sNOME_FANTASIA + '%'  
	AND E.TX_RAZAO_SOCIAL like '%' + @sRAZAO_SOCIAL + '%'  
	AND ISNULL(TE.CEA_ESTADO,0) = COALESCE(@CEA_ESTADO, ISNULL(TE.CEA_ESTADO,0))  
	AND ISNULL(TE.CEA_CATEGORIA,0) = COALESCE(@CEA_CATEGORIA, ISNULL(TE.CEA_CATEGORIA,0))  
	AND ISNULL(TE.CEA_NIVEL_ESCOLARIDADE,0) = COALESCE(@CEA_NIVEL_ESCOLARIDADE, ISNULL(TE.CEA_NIVEL_ESCOLARIDADE,0) )  
	AND ISNULL(TE.CEA_FAIXA_ETARIA,0) = COALESCE(@CEA_FAIXA_ETARIA, ISNULL(TE.CEA_FAIXA_ETARIA,0))  
	AND ISNULL(TE.CEA_CIDADE,0) = COALESCE(@CEA_CIDADE, ISNULL(TE.CEA_CIDADE,0))  
	AND ISNULL(trcer.CEA_ESCRITORIO_REGIONAL, 0) = COALESCE(@CEA_ESCRITORIO_REGIONAL, ISNULL(trcer.CEA_ESCRITORIO_REGIONAL, 0))  
	AND ISNULL(ETTEMP.CEA_TIPO_ETAPA, 0) = COALESCE(@STATUS, ISNULL(ETTEMP.CEA_TIPO_ETAPA, 0))  
	AND ISNULL(TE.CEA_TURMA, 0) = COALESCE(@CEA_TURMA, ISNULL(TE.CEA_TURMA, 0))  
	AND ISNULL(GE.CEA_GRUPO, 0) = COALESCE(@CEA_GRUPO, ISNULL(GE.CEA_GRUPO, 0))  
	AND ISNULL(TE.CEA_FATURAMENTO, 0) = COALESCE(@CEA_FATURAMENTO, ISNULL(TE.CEA_FATURAMENTO, 0))
	AND ISNULL(QE.TX_PROTOCOLO, '') like '%' + @PROTOCOLO + '%'  
	AND E.TX_CPF_CNPJ like '%' + @CPF_CNPJ + '%'  
	AND ISNULL(ter2.CDA_ESTADO_REGIAO, 0) = COALESCE(@CEA_ESTADO_REGIAO, ISNULL(ter2.CDA_ESTADO_REGIAO, 0))  
	AND ISNULL(TE.TX_SEXO_CONTATO, 0) = COALESCE(@TX_SEXO_CONTATO, ISNULL(TE.TX_SEXO_CONTATO, 0))  
	AND TE.DT_ULTIMA_ALTERACAO BETWEEN @DATAINICIO AND @DATAFIM  
	AND ISNULL(TE.NU_FUNCIONARIO, 0) = COALESCE(@NU_FUNCIONARIOS, ISNULL(TE.NU_FUNCIONARIO, 0))  
	AND ISNULL(TE.CEA_TIPO_EMPRESA, 0) =  COALESCE(@TIPO_EMPRESA, ISNULL(TE.CEA_TIPO_EMPRESA, 0))  
	AND TE.FL_PARTICIPA_PROGRAMA = @FL_PARTICIPA_PROGRAMA  
	AND te.FL_ATIVO = 1  

RETURN  
END  
    
--
