USE [SISTEMA GESTAO_desenv]
GO
/****** Object:  StoredProcedure [dbo].[STP_SelecionaArquivoPorFiltrosAdministrativo]    Script Date: 02/17/2011 17:42:52 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[STP_SelecionaArquivoPorFiltrosAdministrativo]
(
@IdUsuario INT,
@IdEstado INT,
@IdPrograma INT,
@IdTurma INT
,@Titulo VARCHAR(255),
@DataInicio DATETIME,
@DataFim DATETIME
)
As    
BEGIN     

SET NOCOUNT ON  

SELECT [CDA_ARQUIVO]
      ,[CEA_ESTADO]
      ,[CEA_PROGRAMA]
      ,[CEA_TURMA]
      ,[NUM_PRIORIDADE]
      ,[TX_TITULO]
      ,[TX_CAMINHO]
      ,[DT_CADASTRO]
      ,[DT_ALTERACAO]
      ,[FL_ATIVO]
      ,[FL_USUARIO_ADMINISTRATIVO]
  FROM [TBL_ARQUIVO] N 
  INNER JOIN (SELECT DISTINCT URGU.CEA_USUARIO, AG.CEA_ARQUIVO FROM TBL_REL_ARQUIVO_ADM_GRUPO AG INNER JOIN TBL_ADM_RELGRUPOUSUARIO RGU ON RGU.CEA_GRUPO = AG.CEA_GRUPO 
				INNER JOIN TBL_ADM_USUARIORELGRUPOUSUARIO URGU ON URGU.CEA_RELGRUPOUSUARIO = RGU.CDA_RELGRUPOUSUARIO
				WHERE URGU.CEA_USUARIO = @IdUsuario) TEMP ON TEMP.CEA_ARQUIVO = N.CDA_ARQUIVO
  WHERE (CEA_ESTADO IS NULL OR CEA_ESTADO = @IdEstado) AND (CEA_PROGRAMA IS NULL OR CEA_PROGRAMA = @IdPrograma)
		 AND (CEA_TURMA IS NULL OR CEA_TURMA = @IdTurma OR @IdTurma = 0) AND N.FL_ATIVO = 1 AND N.FL_USUARIO_ADMINISTRATIVO = 1
		 AND TX_TITULO LIKE '%' + @Titulo + '%' AND DT_CADASTRO BETWEEN @DataInicio AND @DataFim
ORDER BY N.NUM_PRIORIDADE, [DT_CADASTRO] DESC		 
  
RETURN  

END
