SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[STP_AtualizaQuestionarioEmpresaMudarTurmaEtapa]
 @nCDA_QUESTIONARIO_EMPRESA INT,  
 @nCEA_ETAPA INT
As    
BEGIN     
  
SET NOCOUNT ON  

	UPDATE 
		TBL_QUESTIONARIO_EMPRESA 
	SET 
		CEA_ETAPA = @nCEA_ETAPA
	WHERE 
		CDA_QUESTIONARIO_EMPRESA = @nCDA_QUESTIONARIO_EMPRESA  
		  
RETURN  
END
