alter PROCEDURE [dbo].[STP_SelecionaQuestionarioEmpresaRelatorioRAAPorFiltros]    
(  
 @nIdEmpresaCadastro int,    
 @nIdTurma int,    
 @nIdQuestionario int    
)  
As      
BEGIN       
SET NOCOUNT ON    
  
SELECT TOP 1 TBL_QUESTIONARIO_EMPRESA.[CDA_QUESTIONARIO_EMPRESA]  
      ,TBL_QUESTIONARIO_EMPRESA.[CEA_PROGRAMA]  
      ,TBL_QUESTIONARIO_EMPRESA.[CEA_EMP_CADASTRO]  
      ,TBL_QUESTIONARIO_EMPRESA.[DT_CADASTRO]  
      ,TBL_QUESTIONARIO_EMPRESA.[FL_ATIVO]  
      ,TBL_QUESTIONARIO_EMPRESA.[TX_PROTOCOLO]  
      ,TBL_QUESTIONARIO_EMPRESA.[CEA_USUARIO]  
      ,TBL_QUESTIONARIO_EMPRESA.[DT_ALTERACAO]  
      ,TBL_QUESTIONARIO_EMPRESA.[TX_MOTIVO_VENCEU]  
      ,TBL_QUESTIONARIO_EMPRESA.[TX_MOTIVO_EXCLUIU]  
      ,TBL_QUESTIONARIO_EMPRESA.[FL_LEITURA]  
      ,TBL_QUESTIONARIO_EMPRESA.[NU_TOTAL_PONTUACAO]  
      ,TBL_QUESTIONARIO_EMPRESA.[FL_SINCRONIZADO_SIAC]  
      ,TBL_QUESTIONARIO_EMPRESA.[CEA_ETAPA]  
      ,TBL_QUESTIONARIO_EMPRESA.[FL_PASSA_PROXIMA_ETAPA]  
      ,TBL_QUESTIONARIO_EMPRESA.[CEA_QUESTIONARIO]  
      ,TBL_QUESTIONARIO_EMPRESA.[FL_PREENCHE_QUESTIONARIO]  
      ,TBL_QUESTIONARIO_EMPRESA.[CEA_QUESTIONARIO_EMPRESA_PAI]  
      ,TBL_QUESTIONARIO_EMPRESA.[NU_TOTAL_PONTUACAO_AVALIADOR]  
      ,TBL_QUESTIONARIO_EMPRESA.[FL_PARA_AVALIACAO]  
      ,TBL_QUESTIONARIO_EMPRESA.FL_ENVIAR_QUESTIONARIO
      ,TBL_QUESTIONARIO_EMPRESA.FL_RELATORIO_GERADO
 FROM TBL_TURMA    
   INNER JOIN TBL_TURMA_EMP ON TBL_TURMA.CDA_TURMA = TBL_TURMA_EMP.CEA_TURMA    
   INNER JOIN TBL_QUESTIONARIO_EMPRESA ON TBL_TURMA_EMP.CEA_EMP_CADASTRO = TBL_QUESTIONARIO_EMPRESA.CEA_EMP_CADASTRO  
   INNER JOIN TBL_QUESTIONARIO_PONTUACAO ON TBL_QUESTIONARIO_EMPRESA.CDA_QUESTIONARIO_EMPRESA = TBL_QUESTIONARIO_PONTUACAO.CEA_QUESTIONARIO_EMPRESA    
 WHERE TBL_QUESTIONARIO_PONTUACAO.CEA_QUESTIONARIO = @nIdQuestionario    
 AND TBL_TURMA_EMP.CEA_EMP_CADASTRO = @nIdEmpresaCadastro    
 AND TBL_TURMA.CDA_TURMA = @nIdTurma    
 AND TBL_QUESTIONARIO_EMPRESA.FL_ATIVO = 1   
 AND TBL_QUESTIONARIO_EMPRESA.TX_PROTOCOLO is not null  
RETURN    
END    
      
--  