USE [Sistema Gestao]
GO
/****** Object:  StoredProcedure [dbo].[STP_SelecionaUsuarioPorFuncionalidade]    Script Date: 02/16/2011 11:46:58 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[STP_SelecionaUsuarioPorFuncionalidade]
(
	@sNOME_PAGINA VARCHAR(200),
	@nCEA_ESTADO INT,
	@nCEA_PROGRAMA INT,
	@nCEA_TURMA INT
)
As   
BEGIN     
SET NOCOUNT ON  

SELECT DISTINCT
		 TAU.CDA_USUARIO,
		 TAU.TX_USUARIO,
		 TAU.TX_LOGIN,
		 TAU.TX_SENHA,
		 TAU.CEA_ESTADO,
		 TAU.FL_ATIVO,
		 TAU.TX_CPF,
		 TAU.TX_TELEFONE,
		 TAU.TX_EMAIL,
		 TE.TX_ESTADO
	FROM TBL_ADM_USUARIO tau
   INNER JOIN TBL_ADM_USUARIORELGRUPOUSUARIO tau3 ON TAU3.CEA_USUARIO = TAU.CDA_USUARIO
   INNER JOIN TBL_ADM_RELGRUPOUSUARIO tar ON tar.CDA_RELGRUPOUSUARIO = tau3.CEA_RELGRUPOUSUARIO
   INNER JOIN TBL_ADM_RELFUNCGRUPO RFG ON RFG.CEA_GRUPO = TAR.CEA_GRUPO
   INNER JOIN TBL_ADM_FUNCIONALIDADE F ON F.CDA_FUNCIONALIDADE = RFG.CEA_FUNCIONALIDADE
   LEFT JOIN TBL_ESTADO te ON (TAR.CEA_ESTADO = TAU.CEA_ESTADO)
   WHERE tar.CEA_PROGRAMA = @nCEA_PROGRAMA
	 AND ISNULL(TAR.CEA_TURMA, 0) = COALESCE(@nCEA_TURMA, ISNULL(TAR.CEA_TURMA, 0))
	 AND (ISNULL(TAR.CEA_ESTADO, 0) = COALESCE(@nCEA_ESTADO, ISNULL(TAR.CEA_ESTADO, 0)) OR TAR.CEA_ESTADO IS NULL)
	 AND F.TX_FUNCIONALIDADE = @sNOME_PAGINA
	 AND tau.FL_ATIVO = 'TRUE';
	   
   
  
RETURN  
END  
    
--    
