USE [Sistema Gestao]
GO
/****** Object:  StoredProcedure [dbo].[STP_AtualizaQuestionarioEmpresaSomenteFlagLeitura]    Script Date: 02/16/2011 10:50:07 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[STP_AtualizaQuestionarioEmpresaSomenteDesclassificar]
 @nCDA_QUESTIONARIO_EMPRESA INT,  
 @bFL_DESCLASSIFICAR BIT,
 @sTX_MOTIVO_DESCLASSIFICAR NTEXT
As    
BEGIN     
  
SET NOCOUNT ON  

	UPDATE 
		TBL_QUESTIONARIO_EMPRESA 
	SET 
		FL_EXCLUIDO = @bFL_DESCLASSIFICAR,
		FL_PARA_AVALIACAO = @bFL_DESCLASSIFICAR,
		TX_MOTIVO_EXCLUIU = @sTX_MOTIVO_DESCLASSIFICAR 
	WHERE 
		CDA_QUESTIONARIO_EMPRESA = @nCDA_QUESTIONARIO_EMPRESA  
		  
RETURN  
END  
   
   