USE [Sistema Gestao]
GO
/****** Object:  StoredProcedure [dbo].[STP_SelecionaUsuarioPorFiltro]    Script Date: 02/11/2011 18:54:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [dbo].[STP_SelecionaUsuarioPorFiltro]
(
	@nCDA_USUARIO INT,
	@nCDA_PROGRAMA INT,
	@sTX_USUARIO VARCHAR(200),
	@sTX_LOGIN VARCHAR(200),
	@nCEA_ESTADO INT,
	@bFL_ATIVO BIT,
	@sTX_CPF VARCHAR(11),
	@sTX_TELEFONE VARCHAR(40),
	@sTX_EMAIL VARCHAR(200)
)
As   
BEGIN     
SET NOCOUNT ON  

SELECT DISTINCT
		 TAU2.CDA_USUARIO,
		 TAU2.TX_USUARIO,
		 TAU2.TX_LOGIN,
		 TAU2.TX_SENHA,
		 TAU2.CEA_ESTADO,
		 TAU2.FL_ATIVO,
		 TAU2.TX_CPF,
		 TAU2.TX_TELEFONE,
		 TAU2.TX_EMAIL,
		 TE2.TX_ESTADO
	FROM TBL_ADM_USUARIO tau
   INNER JOIN TBL_ADM_USUARIORELGRUPOUSUARIO tau3 ON TAU3.CEA_USUARIO = TAU.CDA_USUARIO AND TAU3.CEA_USUARIO = @nCDA_USUARIO
   INNER JOIN TBL_ADM_RELGRUPOUSUARIO tar ON tar.CDA_RELGRUPOUSUARIO = tau3.CEA_RELGRUPOUSUARIO
   INNER JOIN TBL_ADM_USUARIO TAU2 ON TAU2.CEA_ESTADO = TAR.CEA_ESTADO OR TAR.CEA_ESTADO IS NULL
   INNER JOIN TBL_ESTADO te2 ON (te2.CDA_ESTADO = TAU2.CEA_ESTADO)
   WHERE tar.CEA_PROGRAMA = @nCDA_PROGRAMA
     AND tau2.TX_USUARIO like '%' + @sTX_USUARIO + '%'
     AND tau2.TX_LOGIN like '%' + @sTX_LOGIN + '%'
	 AND tau2.TX_CPF like '%' + @sTX_CPF + '%'
	 AND tau2.TX_TELEFONE like '%' + @sTX_TELEFONE + '%'
	 AND tau2.TX_EMAIL like '%' + @sTX_EMAIL + '%'
	 AND ISNULL(te2.CDA_ESTADO, 0) = COALESCE(@nCEA_ESTADO, ISNULL(te2.CDA_ESTADO, 0))
	 AND tau2.FL_ATIVO = @bFL_ATIVO;
	   
   
  
RETURN  
END  
    
--    
