SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[STP_SelecionaEtapaAtivaPorEstadoTurma]  
(  
@nCEA_ESTADO INT,  
@nCEA_TURMA INT,  
@nCEA_TIPO_ETAPA INT
)  
As      
BEGIN       
  
SET NOCOUNT ON    
  
SELECT [CDA_ETAPA]  
      ,[TX_ETAPA]  
      ,[CEA_TURMA]  
      ,E.[FL_ATIVO]  
      ,[CEA_TIPO_ETAPA]  
      ,[CEA_ESTADO]  
      ,TE.TX_TIPO_ETAPA
      ,ISNULL(ES.TX_ESTADO,'Nacional') AS TX_ESTADO
  FROM [TBL_ETAPA]  E
  INNER JOIN TBL_TIPO_ETAPA TE ON TE.CDA_TIPO_ETAPA = E.CEA_TIPO_ETAPA
  LEFT JOIN TBL_ESTADO ES ON ES.CDA_ESTADO = E.CEA_ESTADO
  WHERE (CEA_ESTADO = @nCEA_ESTADO OR CEA_ESTADO IS NULL) AND E.CEA_TIPO_ETAPA = @nCEA_TIPO_ETAPA AND CEA_TURMA = @nCEA_TURMA  
  ORDER BY TE.NU_ORDEM_FLUXO;
    
RETURN    
  
END    
      
--
