USE [Sistema Gestao]
GO
/****** Object:  StoredProcedure [dbo].[STP_SelecionaQuestionariosEnviadosPorTurmaEmpresa]    Script Date: 02/08/2011 22:03:35 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [dbo].[STP_SelecionaQuestionariosEnviadosPorTurmaEmpresa]
(
 @nIdTurma INT,
 @nIdEmpCadastro INT
)
As    
BEGIN     
SET NOCOUNT ON  

	SELECT q.CDA_QUESTIONARIO,
		   q.TX_QUESTIONARIO,
		   q.TX_DESCRICAO,
		   q.FL_ATIVO,
		   q.FL_PUBLICADO,
		   qe.FL_PREENCHE_QUESTIONARIO,
		   q.NU_CICLO,
		   q.DT_QUESTIONARIO,
		   rtq.FL_OBRIGATORIO,
		   q.FL_PREENCHIMENTO_RAPIDO,
		   qe.TX_PROTOCOLO
	  FROM TBL_REL_TURMA_QUESTIONARIO rtq
INNER JOIN TBL_QUESTIONARIO q ON q.CDA_QUESTIONARIO = rtq.CEA_QUESTIONARIO
INNER JOIN (SELECT * FROM TBL_QUESTIONARIO_EMPRESA WHERE CEA_EMP_CADASTRO = @nIdEmpCadastro AND TX_PROTOCOLO IS NOT NULL AND FL_ATIVO = 'True') qe ON qe.CEA_QUESTIONARIO = q.CDA_QUESTIONARIO 
AND QE.CEA_ETAPA IN (SELECT CDA_ETAPA FROM TBL_ETAPA WHERE CEA_TURMA = @nIdTurma)
	 WHERE rtq.CEA_TURMA = @nIdTurma AND q.FL_PUBLICADO = 'True'
  ORDER BY qe.DT_ALTERACAO DESC, rtq.FL_OBRIGATORIO DESC, q.TX_QUESTIONARIO
  
RETURN  
END  
    
--    
