SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[STP_SelecionaAvaliacaoPorFiltro]
(
@CEA_TIPO_ETAPA INT,
@CEA_TURMA INT,
-------QUESTIONARIOS----------------------
@CEA_QUESTIONARIO_GESTAO INT,
@CEA_QUESTIONARIO_INOVACAO INT,
@CEA_QUESTIONARIO_EMPREENDEDORISMO INT,
@CEA_QUESTIONARIO_RESPONSABILIDADE_SOCIAL INT,
--------FILTROS DE TELA-------------------
@sNOME_FANTASIA VARCHAR(500),
@CEA_ESTADO INT,
@CEA_CATEGORIA INT,
@CEA_NIVEL_ESCOLARIDADE INT,
@CEA_FAIXA_ETARIA INT,
@CEA_CIDADE INT,
@CEA_ESCRITORIO_REGIONAL INT,
@STATUS INT,
@CEA_GRUPO INT,
@CEA_FATURAMENTO INT,
@PROTOCOLO VARCHAR(200),
@CPF_CNPJ VARCHAR(200),
@CEA_ESTADO_REGIAO INT,
@TX_SEXO_CONTATO VARCHAR(1),
@DATAINICIO DATETIME,
@DATAFIM DATETIME,
@NU_FUNCIONARIOS INT,
@TIPO_EMPRESA INT
------------------------------------------
)
As   
BEGIN     

SET NOCOUNT ON  

---------------------------------
						
SELECT DISTINCT
EC.CDA_EMP_CADASTRO,
QE.CDA_QUESTIONARIO_EMPRESA,
EC.TX_CPF_CNPJ,
EC.TX_RAZAO_SOCIAL,
QE.TX_PROTOCOLO,
QE.DT_ALTERACAO,
ES.TX_SIGLA,
'' AS TX_MOTIVO_DEVOLUCAO,
QE.FL_EXCLUIDO [Devolvido],
QE.CEA_ETAPA,
QEA.FL_AVALIADO,
--Possui Questionário de Responsabilidade Social----------       
ISNULL((SELECT 1 FROM TBL_QUESTIONARIO_EMPRESA QRESP WHERE QRESP.CEA_EMP_CADASTRO = EC.CDA_EMP_CADASTRO AND QRESP.FL_ATIVO = 1 AND QRESP.CEA_QUESTIONARIO = @CEA_QUESTIONARIO_RESPONSABILIDADE_SOCIAL AND QE.TX_PROTOCOLO is Not Null AND CEA_ETAPA = QE.CEA_ETAPA), 0) [PossuiResponsabilidadeSocial],
----------------------------------------------------------
--Possui do Questionário de Inovação------------        
ISNULL((SELECT 1 FROM TBL_QUESTIONARIO_EMPRESA QINOVA WHERE QINOVA.CEA_EMP_CADASTRO = EC.CDA_EMP_CADASTRO AND QINOVA.FL_ATIVO = 1 AND QINOVA.CEA_QUESTIONARIO = @CEA_QUESTIONARIO_INOVACAO AND QE.TX_PROTOCOLO is Not Null AND CEA_ETAPA = QE.CEA_ETAPA), 0) [PossuiInovacao]
------------------------------------------------------------------------
FROM TBL_TURMA_EMP TE
JOIN TBL_EMP_CADASTRO EC ON EC.CDA_EMP_CADASTRO = TE.CEA_EMP_CADASTRO
JOIN TBL_QUESTIONARIO_EMPRESA QE ON QE.CEA_EMP_CADASTRO = TE.CEA_EMP_CADASTRO
JOIN (SELECT * FROM TBL_QUESTIONARIO_EMPRESA_AVALIADOR WHERE FL_PRIMARIO = 1) QEA ON QEA.CEA_QUESTIONARIO_EMPRESA = QE.CDA_QUESTIONARIO_EMPRESA
JOIN TBL_ETAPA ET ON ET.CDA_ETAPA = QE.CEA_ETAPA
JOIN TBL_TIPO_ETAPA TIE ON TIE.CDA_TIPO_ETAPA = ET.CEA_TIPO_ETAPA
------------------------------------------------------------------------ 
-----------FILTROS DE TELA----------------------------------------------
JOIN TBL_CARGO CA ON CA.CDA_CARGO = TE.CEA_CARGO        
JOIN TBL_BAIRRO BA ON BA.CDA_BAIRRO = TE.CEA_BAIRRO
JOIN TBL_CIDADE CI ON CI.CDA_CIDADE = TE.CEA_CIDADE
JOIN TBL_ESTADO ES ON ES.CDA_ESTADO = TE.CEA_ESTADO
JOIN TBL_TIPO_EMP TI ON TI.CDA_TIPO_EMPRESA = TE.CEA_TIPO_EMPRESA
JOIN TBL_FATURAMENTO FA ON FA.CDA_FATURAMENTO = TE.CEA_FATURAMENTO
JOIN TBL_CATEGORIA CAT ON CAT.CDA_CATEGORIA = TE.CEA_CATEGORIA
JOIN TBL_ATIVIDADE_ECONOMICA AE ON AE.CDA_ATIVIDADE_ECONOMICA = TE.CEA_ATIVIDADE_ECONOMICA
JOIN TBL_CONTATO_NIVEL_ESCOLARIDADE NE ON NE.CDA_NIVEL_ESCOLARIDADE = TE.CEA_NIVEL_ESCOLARIDADE
JOIN TBL_CONTATO_FAIXA_ETARIA FE ON FE.CDA_FAIXA_ETARIA = TE.CEA_FAIXA_ETARIA
LEFT JOIN TBL_REL_CIDADE_ESCRITORIO_REGIONAL CER ON CER.CEA_CIDADE = CI.CDA_CIDADE
LEFT JOIN TBL_ESCRITORIO_REGIONAL ER ON ER.CDA_ESCRITORIO_REGIONAL = CER.CEA_ESCRITORIO_REGIONAL AND ER.CEA_TURMA = TE.CEA_TURMA
LEFT JOIN TBL_GRUPOEMPRESA GE ON GE.CEA_EMP_CADASTRO = EC.CDA_EMP_CADASTRO
LEFT JOIN TBL_ESTADO_REGIAO ESR ON ESR.CDA_ESTADO_REGIAO = ES.CDA_ESTADO
-----------------------------------------------------------------------------
WHERE ET.CEA_TIPO_ETAPA = @CEA_TIPO_ETAPA
AND EC.FL_ATIVO = 1
AND TE.FL_ATIVO = 1
AND QE.FL_ATIVO = 1
AND QE.TX_PROTOCOLO is Not Null
AND QE.CEA_QUESTIONARIO = @CEA_QUESTIONARIO_GESTAO
AND TE.CEA_TURMA = @CEA_TURMA
------------------------------FILTROS DE TELA------------------------------
AND EC.TX_NOME_FANTASIA like '%' + @sNOME_FANTASIA + '%'
AND TE.CEA_ESTADO = COALESCE(@CEA_ESTADO, TE.CEA_ESTADO)
AND TE.CEA_CATEGORIA = COALESCE(@CEA_CATEGORIA, TE.CEA_CATEGORIA)
AND TE.CEA_NIVEL_ESCOLARIDADE = COALESCE(@CEA_NIVEL_ESCOLARIDADE, TE.CEA_NIVEL_ESCOLARIDADE )
AND TE.CEA_FAIXA_ETARIA = COALESCE(@CEA_FAIXA_ETARIA, TE.CEA_FAIXA_ETARIA)
AND TE.CEA_CIDADE = COALESCE(@CEA_CIDADE, TE.CEA_CIDADE)
AND ISNULL(ER.CDA_ESCRITORIO_REGIONAL, 0) = COALESCE(@CEA_ESCRITORIO_REGIONAL, ISNULL(ER.CDA_ESCRITORIO_REGIONAL, 0))
AND ISNULL(TE.STATUS, 0) = COALESCE(@STATUS, ISNULL(TE.STATUS, 0))
AND ISNULL(GE.CEA_GRUPO, 0) = COALESCE(@CEA_GRUPO, ISNULL(GE.CEA_GRUPO, 0))
AND ISNULL(TE.CEA_FATURAMENTO, 0) = COALESCE(@CEA_FATURAMENTO, ISNULL(TE.CEA_FATURAMENTO, 0))
AND ISNULL(QE.TX_PROTOCOLO, '') like '%' + @PROTOCOLO + '%'
AND EC.TX_CPF_CNPJ like '%' + @CPF_CNPJ + '%'
AND ISNULL(ESR.CDA_ESTADO_REGIAO, 0) = COALESCE(@CEA_ESTADO_REGIAO, ISNULL(ESR.CDA_ESTADO_REGIAO, 0))
AND ISNULL(TE.TX_SEXO_CONTATO, 0) = COALESCE(@TX_SEXO_CONTATO, ISNULL(TE.TX_SEXO_CONTATO, 0))
AND TE.DT_ULTIMA_ALTERACAO BETWEEN @DATAINICIO AND @DATAFIM
AND ISNULL(TE.NU_FUNCIONARIO, 0) = COALESCE(@NU_FUNCIONARIOS, ISNULL(TE.NU_FUNCIONARIO, 0))
AND ISNULL(TE.CEA_TIPO_EMPRESA, 0) =  COALESCE(@TIPO_EMPRESA, ISNULL(TE.CEA_TIPO_EMPRESA, 0))
-----------------------------------------------------------------------------

RETURN  
END  
    
--
