SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[STP_SelecionaAdmGrupoRelUsuarioPorIdGrupo]
(  
    @nCEA_GRUPO int,  
    @nCEA_PROGRAMA INT,
    @nCEA_USUARIO INT   
)  
As      
BEGIN      

SET NOCOUNT ON  

DECLARE @nEstado INT
SET @nEstado = (SELECT COUNT (distinct tar.CEA_ESTADO)
							  FROM TBL_ADM_USUARIO tau 
							  INNER JOIN TBL_ADM_USUARIORELGRUPOUSUARIO tau2 ON tau2.CEA_USUARIO = tau.CDA_USUARIO
							  INNER JOIN TBL_ADM_RELGRUPOUSUARIO tar ON tar.CDA_RELGRUPOUSUARIO = tau2.CEA_RELGRUPOUSUARIO OR tar.CEA_ESTADO IS null
							 WHERE tau.CDA_USUARIO = @nCEA_USUARIO);

 SELECT DISTINCT 
		tar2.CEA_GRUPO,  
		tar2.CDA_RELGRUPOUSUARIO,  
		tar2.CEA_ESCRITORIO_REGIONAL,  
		tar2.CEA_ESTADO,  
		tar2.CEA_TURMA,  
		tar2.CEA_PROGRAMA
   FROM TBL_ADM_RELGRUPOUSUARIO  tar2
   INNER JOIN TBL_ADM_USUARIORELGRUPOUSUARIO tau ON tau.CEA_RELGRUPOUSUARIO = tar2.CDA_RELGRUPOUSUARIO
   INNER JOIN TBL_ADM_USUARIO tau2 ON tau2.CDA_USUARIO = tau.CEA_USUARIO OR tau2.CEA_ESTADO IS null
   
  WHERE tar2.CEA_GRUPO = @nCEA_GRUPO
    AND tar2.CEA_PROGRAMA = @nCEA_PROGRAMA  
    AND (tar2.CEA_ESTADO in (SELECT DISTINCT tar.CEA_ESTADO
							  FROM TBL_ADM_USUARIO tau 
							  INNER JOIN TBL_ADM_USUARIORELGRUPOUSUARIO tau2 ON tau2.CEA_USUARIO = tau.CDA_USUARIO
							  INNER JOIN TBL_ADM_RELGRUPOUSUARIO tar ON tar.CDA_RELGRUPOUSUARIO = tau2.CEA_RELGRUPOUSUARIO OR tar.CEA_ESTADO IS null
							 WHERE tau.CDA_USUARIO = @nCEA_USUARIO) 
							 OR ((SELECT TOP 1 tar.CEA_ESTADO
							  FROM TBL_ADM_USUARIO tau 
							  INNER JOIN TBL_ADM_USUARIORELGRUPOUSUARIO tau2 ON tau2.CEA_USUARIO = tau.CDA_USUARIO
							  INNER JOIN TBL_ADM_RELGRUPOUSUARIO tar ON tar.CDA_RELGRUPOUSUARIO = tau2.CEA_RELGRUPOUSUARIO OR tar.CEA_ESTADO IS null
							 WHERE tau.CDA_USUARIO = @nCEA_USUARIO) IS NULL))
RETURN  

END  
    
--
