USE [SISTEMA GESTAO_desenv]
GO
/****** Object:  StoredProcedure [dbo].[STP_SelecionaNoticiaPorFiltro]    Script Date: 02/17/2011 18:22:30 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[STP_SelecionaNoticiaPorFiltro]
(
@Titulo VARCHAR(255),
@DataInicio DATETIME,
@DataFim DATETIME,
@TipoUsuario BIT,
@IdGrupo INT,
@IdEstado INT,
@IdPrograma INT,
@IdTurma INT,
@FL_ATIVO BIT
)
As    
BEGIN     

SET NOCOUNT ON  

SELECT [CDA_NOTICIA]
      ,N.CEA_ESTADO
      ,N.CEA_PROGRAMA
      ,N.CEA_TURMA
      ,[TX_TITULO]
      ,[TX_IMAGEM_URL]
      ,[TX_CONTEUDO]
      ,N.DT_CADASTRO
      ,[DT_ALTERACAO]
      ,N.FL_ATIVO
      ,[FL_USUARIO_ADMINISTRATIVO]
      ,DT_VIGENCIA_FIM
      ,ISNULL(TX_ESTADO, 'Todos') AS TX_ESTADO
      ,ISNULL(TX_PROGRAMA, 'Todos') AS TX_PROGRAMA
      ,ISNULL(TX_CICLO,'Todas') AS TX_CICLO
  FROM [TBL_NOTICIA] N 
  LEFT JOIN (SELECT DISTINCT CEA_NOTICIA FROM TBL_REL_NOTICIA_ADM_GRUPO WHERE @TipoUsuario = 0 OR (@IdGrupo IS NULL OR CEA_GRUPO = @IdGrupo)) NAG ON NAG.CEA_NOTICIA = N.CDA_NOTICIA
  LEFT JOIN TBL_ESTADO E ON E.CDA_ESTADO = N.CEA_ESTADO
  LEFT JOIN TBL_PROGRAMA P ON P.CDA_PROGRAMA = N.CEA_PROGRAMA
  LEFT JOIN TBL_TURMA T ON T.CDA_TURMA = N.CEA_TURMA
  WHERE (N.CEA_ESTADO IS NULL OR N.CEA_ESTADO = @IdEstado) AND (N.CEA_PROGRAMA IS NULL OR N.CEA_PROGRAMA = @IdPrograma)
		 AND (N.CEA_TURMA IS NULL OR N.CEA_TURMA = @IdTurma) AND (TX_TITULO LIKE '%' + @Titulo + '%')
		 AND (@DataInicio IS NULL OR N.DT_CADASTRO >= @DataInicio) AND (@DataFim IS NULL OR N.DT_CADASTRO <= @DataFim)
		 AND (@TipoUsuario IS NULL OR FL_USUARIO_ADMINISTRATIVO = @TipoUsuario) AND N.FL_ATIVO = @FL_ATIVO
ORDER BY N.DT_CADASTRO DESC		 
  
RETURN  

END
