/*   
------------------------------------------------------------------------------------------   
Procedure...............: STP_AlterarEtapaDoQuestionarioEmpresa
Funcao..................:  
  
  
Tabelas utilizadas......: TBL_QUESTIONARIO_EMPRESA
Procedures utilizadas ..:   
Criada por..............: Fabio Moraes
Data criacao............: 17/01/2011
Parmetros..............:   
    
Data  Nome   Descricao
---------- ---------------- --------------------------------------------------   
dd/mm/aaaa XXXXXXXX   Alterao de parmetros   

---------- ---------------- --------------------------------------------------   
*/    
DECLARE @NAME_PROCEDURE VARCHAR(250) = 'STP_AlterarEtapaDoQuestionarioEmpresa'

IF NOT EXISTS (SELECT * FROM SYSOBJECTS WHERE ID = OBJECT_ID(@NAME_PROCEDURE) and sysstat & 0xf = 4)
BEGIN
  EXEC ('CREATE PROCEDURE [dbo].['+ @NAME_PROCEDURE +'] AS')
END
GO


ALTER PROCEDURE [dbo].STP_AlterarEtapaDoQuestionarioEmpresa
(
@CEA_TIPO_ETAPA_PROXIMA INT,
@CDA_QUESTIONARIO_EMPRESA INT,
@TX_MOTIVO_VENCEU TEXT,
@IS_INICIO_ETAPA_NACIONAL BIT
)
As   
BEGIN     

SET NOCOUNT ON  

DECLARE @CEA_ESTADO INT
DECLARE @CEA_TURMA INT
DECLARE @CEA_PROXIMA_ETAPA INT

SELECT TOP 1 @CEA_ESTADO = E.CEA_ESTADO, @CEA_TURMA = E.CEA_TURMA
FROM TBL_QUESTIONARIO_EMPRESA QE
JOIN TBL_ETAPA E ON E.CDA_ETAPA = QE.CEA_ETAPA
WHERE QE.CDA_QUESTIONARIO_EMPRESA = @CDA_QUESTIONARIO_EMPRESA

SELECT TOP 1 @CEA_PROXIMA_ETAPA = E.CDA_ETAPA
FROM TBL_ETAPA E
WHERE E.CEA_ESTADO = @CEA_ESTADO AND E.CEA_TURMA = @CEA_TURMA AND E.CEA_TIPO_ETAPA = @CEA_TIPO_ETAPA_PROXIMA

--Insere um novo registro associando a Etapa que foi passada como parametro
INSERT INTO TBL_QUESTIONARIO_EMPRESA
(CEA_PROGRAMA			
,CEA_EMP_CADASTRO				
,DT_CADASTRO
,FL_ATIVO					
,TX_PROTOCOLO					
,CEA_USUARIO
,DT_ALTERACAO				
,TX_MOTIVO_VENCEU				
,TX_MOTIVO_EXCLUIU
,FL_LEITURA					
,NU_TOTAL_PONTUACAO				
,FL_SINCRONIZADO_SIAC
,CEA_ETAPA					
,FL_PASSA_PROXIMA_ETAPA			
,CEA_QUESTIONARIO
,FL_PREENCHE_QUESTIONARIO    
,CEA_QUESTIONARIO_EMPRESA_PAI   
,NU_TOTAL_PONTUACAO_AVALIADOR
,FL_PARA_AVALIACAO)
SELECT  CEA_PROGRAMA		      
,CEA_EMP_CADASTRO   		  
,DT_CADASTRO
,FL_ATIVO				  
,TX_PROTOCOLO				  
,CEA_USUARIO
,DT_ALTERACAO			  
,@TX_MOTIVO_VENCEU			  
,TX_MOTIVO_EXCLUIU
,FL_LEITURA			  
,NU_TOTAL_PONTUACAO
,FL_SINCRONIZADO_SIAC	  
,@CEA_PROXIMA_ETAPA				  
,1
,CEA_QUESTIONARIO		  
,FL_PREENCHE_QUESTIONARIO	  
,CEA_QUESTIONARIO_EMPRESA_PAI
,NU_TOTAL_PONTUACAO_AVALIADOR
,FL_PARA_AVALIACAO
FROM TBL_QUESTIONARIO_EMPRESA 
WHERE CDA_QUESTIONARIO_EMPRESA = @CDA_QUESTIONARIO_EMPRESA
DECLARE @CDA_QUESTIONARIO_EMPRESA_NOVO INT
SET @CDA_QUESTIONARIO_EMPRESA_NOVO = @@IDENTITY

--Atualiza registro setando a FL_PASSA_PROXIMA_ETAPA
UPDATE [TBL_QUESTIONARIO_EMPRESA]
   SET [DT_ALTERACAO] = GETDATE(),
       [FL_PASSA_PROXIMA_ETAPA] = 1
 WHERE CDA_QUESTIONARIO_EMPRESA = @CDA_QUESTIONARIO_EMPRESA

--Replica registros da TBL_QUESTIONARIO_EMPRESA_AVALIADOR 
--utilizando a variavel @CDA_QUESTIONARIO_EMPRESA_NOVO
IF EXISTS (SELECT TOP 1 * FROM [TBL_QUESTIONARIO_EMPRESA_AVALIADOR]
		   WHERE CEA_QUESTIONARIO_EMPRESA = @CDA_QUESTIONARIO_EMPRESA)
BEGIN
	INSERT INTO [TBL_QUESTIONARIO_EMPRESA_AVALIADOR]
	([CEA_QUESTIONARIO_EMPRESA]
	,[CEA_USUARIO]
	,[FL_AVALIADO]
	,[TX_MOTIVO_DEVOLUCAO]
	,[TX_MELHOR_PRATICA]
	,[TX_BANCA]
	,[FL_PRIMARIO])
	SELECT
	 @CDA_QUESTIONARIO_EMPRESA_NOVO
	,[CEA_USUARIO]
	,[FL_AVALIADO]
	,[TX_MOTIVO_DEVOLUCAO]
	,[TX_MELHOR_PRATICA]
	,[TX_BANCA]
	,[FL_PRIMARIO]
	FROM [TBL_QUESTIONARIO_EMPRESA_AVALIADOR]
	WHERE CEA_QUESTIONARIO_EMPRESA = @CDA_QUESTIONARIO_EMPRESA
END

--Replica registros da TBL_QUESTIONARIO_EMPRESA_RESPOSTA 
--utilizando a variavel @CDA_QUESTIONARIO_EMPRESA_NOVO
INSERT INTO [TBL_QUESTIONARIO_EMPRESA_RESPOSTA]
([CEA_QUESTIONARIO_EMPRESA]
,[CEA_PERGUNTA]
,[CEA_RESPOSTA]
,[TX_RESPOSTA]
,[CEA_USUARIO_DIGITADOR]
,[CEA_USUARIO_AVALIADOR]
,[TX_JUSTIFICATIVA]
,[TX_VALOR_02]
,[TX_VALOR_03]
,[TX_VALOR_04]
,[TX_VALOR_05]
,[TX_VALOR_06]
,[TX_VALOR_07]
,[TX_VALOR_08]
,[TX_VALOR_09]
,[TX_VALOR_10]
,[TX_OPORTUNIDADE_MELHORIA]
,[TX_PONTO_FORTE]
,[FL_RESPOSTA_BOOL]
,[TX_VALOR_01])
SELECT @CDA_QUESTIONARIO_EMPRESA_NOVO
,[CEA_PERGUNTA]
,[CEA_RESPOSTA]
,[TX_RESPOSTA]
,[CEA_USUARIO_DIGITADOR]
,[CEA_USUARIO_AVALIADOR]
,[TX_JUSTIFICATIVA]
,[TX_VALOR_02]
,[TX_VALOR_03]
,[TX_VALOR_04]
,[TX_VALOR_05]
,[TX_VALOR_06]
,[TX_VALOR_07]
,[TX_VALOR_08]
,[TX_VALOR_09]
,[TX_VALOR_10]
,[TX_OPORTUNIDADE_MELHORIA]
,[TX_PONTO_FORTE]
,[FL_RESPOSTA_BOOL]
,[TX_VALOR_01]
FROM [TBL_QUESTIONARIO_EMPRESA_RESPOSTA]
WHERE CEA_QUESTIONARIO_EMPRESA = @CDA_QUESTIONARIO_EMPRESA

IF (@IS_INICIO_ETAPA_NACIONAL = 0)
BEGIN

	--Replica registros da TBL_QUESTIONARIO_PONTUACAO 
	--utilizando a variavel @CDA_QUESTIONARIO_EMPRESA_NOVO
	INSERT INTO [TBL_QUESTIONARIO_PONTUACAO]
	([CEA_QUESTIONARIO_EMPRESA]
	,[CEA_CRITERIO]
	,[NU_PONTO]
	,[CEA_QUESTIONARIO]
	,[FL_AVALIADOR])
	SELECT @CDA_QUESTIONARIO_EMPRESA_NOVO
	,[CEA_CRITERIO]
	,[NU_PONTO]
	,[CEA_QUESTIONARIO]
	,[FL_AVALIADOR]
	FROM [TBL_QUESTIONARIO_PONTUACAO]
	WHERE CEA_QUESTIONARIO_EMPRESA = @CDA_QUESTIONARIO_EMPRESA

END
ELSE
BEGIN

	--Replica registros da TBL_QUESTIONARIO_PONTUACAO 
	--utilizando a variavel @CDA_QUESTIONARIO_EMPRESA_NOVO
	INSERT INTO [TBL_QUESTIONARIO_PONTUACAO]
	([CEA_QUESTIONARIO_EMPRESA]
	,[CEA_CRITERIO]
	,[NU_PONTO]
	,[CEA_QUESTIONARIO]
	,[FL_AVALIADOR])
	SELECT @CDA_QUESTIONARIO_EMPRESA_NOVO
	,[CEA_CRITERIO]
	,[NU_PONTO]
	,[CEA_QUESTIONARIO]
	,0
	FROM [TBL_QUESTIONARIO_PONTUACAO]
	WHERE	CEA_QUESTIONARIO_EMPRESA = @CDA_QUESTIONARIO_EMPRESA
	AND	FL_AVALIADOR = 1
	
END

RETURN  
END  
    
--