SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[STP_SelecionaTurmaEmpresaAnteriorPorEmpresaCadastro]
(
@CDA_EMP_CADASTRO INT,  
@CDA_TURMA INT,  
@CEA_PROGRAMA INT  
)
As   
BEGIN     
SET NOCOUNT ON  

 
	SELECT TOP 1 TE.[CEA_EMP_CADASTRO]  
		  ,TE.[CEA_CATEGORIA]  
		  ,TE.[CEA_ATIVIDADE_ECONOMICA]  
		  ,TE.[CEA_FATURAMENTO]  
		  ,TE.[NU_FUNCIONARIO]  
		  ,TE.[TX_CEP]  
		  ,TE.[TX_ENDERECO]  
		  ,TE.TX_NUMERO
		  ,TE.[TX_COMPLEMENTO]  
		  ,TE.[FL_ATIVO]  
		  ,TE.[CEA_USUARIO]  
		  ,TE.[CEA_CIDADE]  
		  ,TE.[DT_ULTIMA_ALTERACAO]  
		  ,TE.[CEA_ESTADO]  
		  ,TE.[CEA_PAIS]  
		  ,TE.[DT_CADASTRO]  
		  ,TE.[TX_ATIVIDADE_ECONOMICA]  
		  ,TE.[FL_PARTICIPA_PROGRAMA]  
		  ,TE.[TX_NOME_CONTATO]  
		  ,TE.[TX_TELEFONE_CONTATO]  
		  ,TE.[TX_CELULAR_CONTATO]  
		  ,TE.[TX_EMAIL_CONTATO]  
		  ,TE.[TX_MENSAGEM_CONTATO]  
		  ,TE.[TX_CPF_CONTATO]  
		  ,TE.[DT_DATA_NASCIMENTO_CONTATO]  
		  ,TE.[TX_ENDERECO_CONTATO]  
		  ,TE.TX_NUMERO_CONTATO
		  ,TE.TX_COMPLEMENTO_CONTATO
		  ,TE.[TX_SEXO_CONTATO]  
		  ,TE.[CEA_NIVEL_ESCOLARIDADE]  
		  ,TE.[CEA_FAIXA_ETARIA]  
		  ,TE.[CEA_TURMA]  
		  ,TE.[CEA_TIPO_EMPRESA]  
		  ,TE.[CEA_BAIRRO]  
		  ,TE.[CEA_CARGO]  
		  ,TE.[TX_CEP_CONTATO]  
		  ,TE.[FL_PERGUNTA1]  
		  ,TE.[FL_PERGUNTA2]  
		  ,TE.[FL_PERGUNTA3]  
		  ,TE.[FL_PERGUNTA4]  
		  ,TE.[CEA_ESTADO_CONTATO]  
		  ,TE.[CEA_CIDADE_CONTATO]  
		  ,TE.[CEA_BAIRRO_CONTATO]  
		  ,TE.[STATUS]  
	 FROM TBL_TURMA_EMP TE  
	JOIN TBL_EMP_CADASTRO EC ON EC.CDA_EMP_CADASTRO = TE.CEA_EMP_CADASTRO  
	JOIN TBL_TURMA T ON T.CDA_TURMA = TE.CEA_TURMA  
	WHERE EC.CDA_EMP_CADASTRO = @CDA_EMP_CADASTRO  
	AND T.CDA_TURMA <> @CDA_TURMA
	AND T.CEA_PROGRAMA = @CEA_PROGRAMA  
	AND TE.FL_ATIVO = 1  
	AND EC.FL_ATIVO = 1  
       
RETURN  
END  
    
--
