USE [Sistema Gestao]
GO
/****** Object:  StoredProcedure [dbo].[STP_SelecionaProximaEtapaPorEtapaEstadoOrdem]    Script Date: 02/14/2011 11:36:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[STP_SelecionaProximaEtapaPorEtapaEstadoOrdem]  
(  
@nCEA_ETAPA INT
)  
As      
BEGIN       
SET NOCOUNT ON    
  
SELECT ET.[CDA_ETAPA]
      ,ET.[TX_ETAPA]
      ,ET.[CEA_TURMA]
      ,ET.[FL_ATIVO]
      ,ET.[CEA_TIPO_ETAPA]
      ,ET.[CEA_ESTADO]
  FROM [TBL_ETAPA] ET 
  INNER JOIN (SELECT * FROM TBL_ETAPA WHERE CDA_ETAPA = @nCEA_ETAPA) ET1 ON ET1.CEA_TURMA = ET.CEA_TURMA
  INNER JOIN TBL_TIPO_ETAPA TE ON TE.CDA_TIPO_ETAPA = ET.CEA_TIPO_ETAPA
  INNER JOIN TBL_TIPO_ETAPA TE1 ON TE1.CDA_TIPO_ETAPA = ET1.CEA_TIPO_ETAPA
  WHERE TE.NU_ORDEM_FLUXO > TE1.NU_ORDEM_FLUXO
    AND (ET.CEA_ESTADO = ET1.CEA_ESTADO OR ET.CEA_ESTADO IS NULL)
  ORDER BY TE.NU_ORDEM_FLUXO ASC
  
    
RETURN    
END
