SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[STP_Siac_AtualizaTipoEmpresa]
 @nCOD_SIAC INT,  
 @nCDA_TIPO_EMPRESA INT
	           
As  
BEGIN   

SET NOCOUNT ON

UPDATE [TBL_TIPO_EMP]
   SET [COD_SIACWEB] = @nCOD_SIAC
 WHERE CDA_TIPO_EMPRESA = @nCDA_TIPO_EMPRESA

RETURN
END
