SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
create PROCEDURE [dbo].[STP_SelecionaRelatorioQuestoesEspeciaisPorFiltro]
(
@CEA_TIPO_ETAPA INT,
@CEA_TURMA INT,
----------CRITERIOS GESTÃO--------------------
@CEA_CRITERIO_CLIENTE INT,
@CEA_CRITERIO_SOCIEDADE INT,
@CEA_CRITERIO_LIDERANCA INT,
@CEA_CRITERIO_ESTRATEGIA_PLANO INT,
@CEA_CRITERIO_PESSOAS INT,
@CEA_CRITERIO_PROCESSOS INT,
@CEA_CRITERIO_INFORMACAO_CONHECIMENTO INT,
@CEA_CRITERIO_RESULTADO_CONTROLE INT,
@FL_AVALIADOR BIT,
@CEA_PERGUNTA_9 INT,
@CEA_PERGUNTA_10 INT,
@CEA_PERGUNTA_11 INT,
@CEA_PERGUNTA_16 INT,
@CEA_PERGUNTA_20 INT,
@CEA_PERGUNTA_23 INT,
@CEA_PERGUNTA_31 INT,
------------------------------------------
-------QUESTIONARIOS----------------------
@CEA_QUESTIONARIO INT,
--------FILTROS DE TELA-------------------
@sRAZAO_SOCIAL VARCHAR(500),
@sNOME_FANTASIA VARCHAR(500),
@CEA_ESTADO INT,
@CEA_CATEGORIA INT,
@CEA_NIVEL_ESCOLARIDADE INT,
@CEA_FAIXA_ETARIA INT,
@CEA_CIDADE INT,
@CEA_ESCRITORIO_REGIONAL INT,
@STATUS INT,
@CEA_GRUPO INT,
@CEA_FATURAMENTO INT,
@PROTOCOLO VARCHAR(200),
@CPF_CNPJ VARCHAR(200),
@CEA_ESTADO_REGIAO INT,
@TX_SEXO_CONTATO VARCHAR(1),
@DATAINICIO DATETIME,
@DATAFIM DATETIME,
@NU_FUNCIONARIOS INT,
@TIPO_EMPRESA INT
------------------------------------------
)
As   
BEGIN     

SET NOCOUNT ON  

SELECT DISTINCT
EC.CDA_EMP_CADASTRO,
QE.CDA_QUESTIONARIO_EMPRESA,
QE.TX_PROTOCOLO,
EC.TX_CPF_CNPJ,
EC.TX_RAZAO_SOCIAL,
ET.CEA_ESTADO,
ET.FL_ATIVO AS FL_ETAPA_ATIVA,
ET.CDA_ETAPA,
------------------------------------------------
------------------------POS-VISITA--------------------------------------
ISNULL(P1, 0) + ISNULL(P2, 0) + ISNULL(P3, 0) + ISNULL(P4, 0) + ISNULL(P5, 0) + ISNULL(P6, 0) + ISNULL(P7, 0) + ISNULL(P8, 0) [PontuacaoTotal],
ISNULL(P1, 0) [CriterioCliente],
ISNULL(P2, 0) [CriterioSociedade],
ISNULL(P3, 0) [CriterioLideranca],
ISNULL(P4, 0) [CriterioEstrategiaPlanos],
ISNULL(P5, 0) [CriterioPessoas],
ISNULL(P6, 0) [CriterioProcessos],
ISNULL(P7, 0) [CriterioInformacoesConhecimento],
ISNULL(P8, 0) [CriterioResultado],

ISNULL(TPR9.NU_PONTO, 0) + ISNULL(TPR10.NU_PONTO, 0) + ISNULL(TPR11.NU_PONTO, 0) + ISNULL(TPR16.NU_PONTO, 0) + ISNULL(TPR20.NU_PONTO, 0) + ISNULL(TPR23.NU_PONTO, 0) + ISNULL(TPR31.NU_PONTO, 0) [PontuacaoQuestoesEspeciais],
ISNULL(TPR9.NU_PONTO, 0) [PontuacaoQuestao9],
ISNULL(TPR9.NU_ORDEM, 0) [RespostaQuestao9],
ISNULL(TPR10.NU_PONTO, 0) [PontuacaoQuestao10],
ISNULL(TPR10.NU_ORDEM, 0) [RespostaQuestao10],
ISNULL(TPR11.NU_PONTO, 0) [PontuacaoQuestao11],
ISNULL(TPR11.NU_ORDEM, 0) [RespostaQuestao11],
ISNULL(TPR16.NU_PONTO, 0) [PontuacaoQuestao16],
ISNULL(TPR16.NU_ORDEM, 0) [RespostaQuestao16],
ISNULL(TPR20.NU_PONTO, 0) [PontuacaoQuestao20],
ISNULL(TPR20.NU_ORDEM, 0) [RespostaQuestao20],
ISNULL(TPR23.NU_PONTO, 0) [PontuacaoQuestao23],
ISNULL(TPR23.NU_ORDEM, 0) [RespostaQuestao23],
ISNULL(TPR31.NU_PONTO, 0) [PontuacaoQuestao31],
ISNULL(TPR31.NU_ORDEM, 0) [RespostaQuestao31]

------------------------------------------------------------------------
FROM TBL_TURMA_EMP TE
JOIN TBL_EMP_CADASTRO EC ON EC.CDA_EMP_CADASTRO = TE.CEA_EMP_CADASTRO
JOIN TBL_QUESTIONARIO_EMPRESA QE ON QE.CEA_EMP_CADASTRO = TE.CEA_EMP_CADASTRO
JOIN TBL_ETAPA ET ON ET.CDA_ETAPA = QE.CEA_ETAPA
JOIN TBL_TIPO_ETAPA TIE ON TIE.CDA_TIPO_ETAPA = ET.CEA_TIPO_ETAPA
------------------------POS-VISITA--------------------------------------
--Critério Cliente--
LEFT JOIN (  SELECT SUM(NU_PONTO) AS P1, CEA_CRITERIO, CEA_QUESTIONARIO_EMPRESA, FL_AVALIADOR    
       FROM  TBL_QUESTIONARIO_PONTUACAO      
       WHERE CEA_CRITERIO = @CEA_CRITERIO_CLIENTE AND FL_AVALIADOR = COALESCE(@FL_AVALIADOR, FL_AVALIADOR)  
       GROUP BY CEA_QUESTIONARIO_EMPRESA, CEA_CRITERIO, FL_AVALIADOR) QP1     
       ON QP1.CEA_QUESTIONARIO_EMPRESA = QE.CDA_QUESTIONARIO_EMPRESA
------------------------
----Critério Sociedade--
LEFT JOIN (  SELECT SUM(NU_PONTO) AS P2, CEA_CRITERIO, CEA_QUESTIONARIO_EMPRESA    
       FROM TBL_QUESTIONARIO_PONTUACAO     
       WHERE CEA_CRITERIO = @CEA_CRITERIO_SOCIEDADE AND FL_AVALIADOR = COALESCE(@FL_AVALIADOR, FL_AVALIADOR)  
       GROUP BY CEA_QUESTIONARIO_EMPRESA, CEA_CRITERIO, FL_AVALIADOR) QP2     
       ON QP2.CEA_QUESTIONARIO_EMPRESA = QE.CDA_QUESTIONARIO_EMPRESA
------------------------
----Critério Liderança--
LEFT JOIN (  SELECT SUM(NU_PONTO) AS P3, CEA_CRITERIO, CEA_QUESTIONARIO_EMPRESA    
       FROM TBL_QUESTIONARIO_PONTUACAO     
       WHERE CEA_CRITERIO = @CEA_CRITERIO_LIDERANCA AND FL_AVALIADOR = COALESCE(@FL_AVALIADOR, FL_AVALIADOR)  
       GROUP BY CEA_QUESTIONARIO_EMPRESA, CEA_CRITERIO, FL_AVALIADOR) QP3     
       ON QP3.CEA_QUESTIONARIO_EMPRESA = QE.CDA_QUESTIONARIO_EMPRESA 
------------------------         
----Critério Estrategia e Planos--
LEFT JOIN (  SELECT SUM(NU_PONTO) AS P4, CEA_CRITERIO, CEA_QUESTIONARIO_EMPRESA    
       FROM TBL_QUESTIONARIO_PONTUACAO     
       WHERE CEA_CRITERIO = @CEA_CRITERIO_ESTRATEGIA_PLANO AND FL_AVALIADOR = COALESCE(@FL_AVALIADOR, FL_AVALIADOR)  
       GROUP BY CEA_QUESTIONARIO_EMPRESA, CEA_CRITERIO, FL_AVALIADOR) QP4     
       ON QP4.CEA_QUESTIONARIO_EMPRESA = QE.CDA_QUESTIONARIO_EMPRESA 
------------------------
----Critério Pessoas--
LEFT JOIN (  SELECT SUM(NU_PONTO) AS P5, CEA_CRITERIO, CEA_QUESTIONARIO_EMPRESA    
       FROM TBL_QUESTIONARIO_PONTUACAO     
       WHERE CEA_CRITERIO = @CEA_CRITERIO_PESSOAS AND FL_AVALIADOR = COALESCE(@FL_AVALIADOR, FL_AVALIADOR)  
       GROUP BY CEA_QUESTIONARIO_EMPRESA, CEA_CRITERIO, FL_AVALIADOR) QP5     
       ON QP5.CEA_QUESTIONARIO_EMPRESA = QE.CDA_QUESTIONARIO_EMPRESA 
------------------------    
----Critério Processos--
   LEFT JOIN (  SELECT SUM(NU_PONTO) AS P6, CEA_CRITERIO, CEA_QUESTIONARIO_EMPRESA    
       FROM TBL_QUESTIONARIO_PONTUACAO     
       WHERE CEA_CRITERIO = @CEA_CRITERIO_PROCESSOS AND FL_AVALIADOR = COALESCE(@FL_AVALIADOR, FL_AVALIADOR)  
       GROUP BY CEA_QUESTIONARIO_EMPRESA, CEA_CRITERIO, FL_AVALIADOR) QP6     
       ON QP6.CEA_QUESTIONARIO_EMPRESA = QE.CDA_QUESTIONARIO_EMPRESA   
------------------------
----Critério Informações e Conhecimento-         
   LEFT JOIN (  SELECT SUM(NU_PONTO) AS P7, CEA_CRITERIO, CEA_QUESTIONARIO_EMPRESA    
       FROM TBL_QUESTIONARIO_PONTUACAO     
       WHERE CEA_CRITERIO = @CEA_CRITERIO_INFORMACAO_CONHECIMENTO AND FL_AVALIADOR = COALESCE(@FL_AVALIADOR, FL_AVALIADOR)  
       GROUP BY CEA_QUESTIONARIO_EMPRESA, CEA_CRITERIO, FL_AVALIADOR) QP7     
       ON QP7.CEA_QUESTIONARIO_EMPRESA = QE.CDA_QUESTIONARIO_EMPRESA     
------------------------
----Critério Resultado de Controle--       
   LEFT JOIN (  SELECT SUM(NU_PONTO) AS P8, CEA_CRITERIO, CEA_QUESTIONARIO_EMPRESA    
       FROM TBL_QUESTIONARIO_PONTUACAO     
       WHERE CEA_CRITERIO = @CEA_CRITERIO_RESULTADO_CONTROLE AND FL_AVALIADOR = COALESCE(@FL_AVALIADOR, FL_AVALIADOR)  
       GROUP BY CEA_QUESTIONARIO_EMPRESA, CEA_CRITERIO, FL_AVALIADOR) QP8     
       ON QP8.CEA_QUESTIONARIO_EMPRESA = QE.CDA_QUESTIONARIO_EMPRESA     
------------------------------------------------------------------------ 
--------------PERGUNTAS-------------------------------------------------
INNER JOIN TBL_QUESTIONARIO_EMPRESA_RESPOSTA QER9 ON QER9.CEA_QUESTIONARIO_EMPRESA = QE.CDA_QUESTIONARIO_EMPRESA AND QER9.FL_AVALIADOR = @FL_AVALIADOR
INNER JOIN TBL_PERGUNTA_RESPOSTA TPR9 ON TPR9.CDA_RESPOSTA = QER9.CEA_RESPOSTA AND TPR9.CEA_PERGUNTA = @CEA_PERGUNTA_9
INNER JOIN TBL_QUESTIONARIO_EMPRESA_RESPOSTA QER10 ON QER10.CEA_QUESTIONARIO_EMPRESA = QE.CDA_QUESTIONARIO_EMPRESA AND QER10.FL_AVALIADOR = @FL_AVALIADOR
INNER JOIN TBL_PERGUNTA_RESPOSTA TPR10 ON TPR10.CDA_RESPOSTA = QER10.CEA_RESPOSTA AND TPR10.CEA_PERGUNTA = @CEA_PERGUNTA_10
INNER JOIN TBL_QUESTIONARIO_EMPRESA_RESPOSTA QER11 ON QER11.CEA_QUESTIONARIO_EMPRESA = QE.CDA_QUESTIONARIO_EMPRESA AND QER11.FL_AVALIADOR = @FL_AVALIADOR
INNER JOIN TBL_PERGUNTA_RESPOSTA TPR11 ON TPR11.CDA_RESPOSTA = QER11.CEA_RESPOSTA AND TPR11.CEA_PERGUNTA = @CEA_PERGUNTA_11
INNER JOIN TBL_QUESTIONARIO_EMPRESA_RESPOSTA QER16 ON QER16.CEA_QUESTIONARIO_EMPRESA = QE.CDA_QUESTIONARIO_EMPRESA AND QER16.FL_AVALIADOR = @FL_AVALIADOR
INNER JOIN TBL_PERGUNTA_RESPOSTA TPR16 ON TPR16.CDA_RESPOSTA = QER16.CEA_RESPOSTA AND TPR16.CEA_PERGUNTA = @CEA_PERGUNTA_16
INNER JOIN TBL_QUESTIONARIO_EMPRESA_RESPOSTA QER20 ON QER20.CEA_QUESTIONARIO_EMPRESA = QE.CDA_QUESTIONARIO_EMPRESA AND QER20.FL_AVALIADOR = @FL_AVALIADOR
INNER JOIN TBL_PERGUNTA_RESPOSTA TPR20 ON TPR20.CDA_RESPOSTA = QER20.CEA_RESPOSTA AND TPR20.CEA_PERGUNTA = @CEA_PERGUNTA_20
INNER JOIN TBL_QUESTIONARIO_EMPRESA_RESPOSTA QER23 ON QER23.CEA_QUESTIONARIO_EMPRESA = QE.CDA_QUESTIONARIO_EMPRESA AND QER23.FL_AVALIADOR = @FL_AVALIADOR
INNER JOIN TBL_PERGUNTA_RESPOSTA TPR23 ON TPR23.CDA_RESPOSTA = QER23.CEA_RESPOSTA AND TPR23.CEA_PERGUNTA = @CEA_PERGUNTA_23
INNER JOIN TBL_QUESTIONARIO_EMPRESA_RESPOSTA QER31 ON QER31.CEA_QUESTIONARIO_EMPRESA = QE.CDA_QUESTIONARIO_EMPRESA AND QER31.FL_AVALIADOR = @FL_AVALIADOR
INNER JOIN TBL_PERGUNTA_RESPOSTA TPR31 ON TPR31.CDA_RESPOSTA = QER31.CEA_RESPOSTA AND TPR31.CEA_PERGUNTA = @CEA_PERGUNTA_31
------------------------------------------------------------------------ 
-----------FILTROS DE TELA----------------------------------------------
JOIN TBL_CARGO CA ON CA.CDA_CARGO = TE.CEA_CARGO        
JOIN TBL_BAIRRO BA ON BA.CDA_BAIRRO = TE.CEA_BAIRRO
JOIN TBL_CIDADE CI ON CI.CDA_CIDADE = TE.CEA_CIDADE
JOIN TBL_ESTADO ES ON ES.CDA_ESTADO = TE.CEA_ESTADO
JOIN TBL_TIPO_EMP TI ON TI.CDA_TIPO_EMPRESA = TE.CEA_TIPO_EMPRESA
JOIN TBL_FATURAMENTO FA ON FA.CDA_FATURAMENTO = TE.CEA_FATURAMENTO
JOIN TBL_CATEGORIA CAT ON CAT.CDA_CATEGORIA = TE.CEA_CATEGORIA
JOIN TBL_ATIVIDADE_ECONOMICA AE ON AE.CDA_ATIVIDADE_ECONOMICA = TE.CEA_ATIVIDADE_ECONOMICA
JOIN TBL_CONTATO_NIVEL_ESCOLARIDADE NE ON NE.CDA_NIVEL_ESCOLARIDADE = TE.CEA_NIVEL_ESCOLARIDADE
JOIN TBL_CONTATO_FAIXA_ETARIA FE ON FE.CDA_FAIXA_ETARIA = TE.CEA_FAIXA_ETARIA
LEFT JOIN TBL_ESCRITORIO_REGIONAL ER ON ER.CEA_ESTADO = ES.CDA_ESTADO
LEFT JOIN TBL_GRUPOEMPRESA GE ON GE.CEA_EMP_CADASTRO = EC.CDA_EMP_CADASTRO
JOIN TBL_ESTADO_REGIAO ESR ON ESR.CDA_ESTADO_REGIAO = ES.CDA_ESTADO
LEFT JOIN TBL_QUESTIONARIO_EMPRESA_AVALIADOR QEA ON QEA.CEA_QUESTIONARIO_EMPRESA = QE.CDA_QUESTIONARIO_EMPRESA AND QEA.FL_PRIMARIO = 1
LEFT JOIN TBL_QUESTIONARIO_EMPRESA_AVALIADOR QEA2 ON QEA2.CEA_QUESTIONARIO_EMPRESA = QE.CDA_QUESTIONARIO_EMPRESA AND QEA2.FL_PRIMARIO = 0
LEFT JOIN TBL_ADM_USUARIO U1 ON U1.CDA_USUARIO = QEA.CEA_USUARIO
LEFT JOIN TBL_ADM_USUARIO U2 ON U2.CDA_USUARIO = QEA2.CEA_USUARIO
-----------------------------------------------------------------------------
WHERE ET.CEA_TIPO_ETAPA = @CEA_TIPO_ETAPA
AND EC.FL_ATIVO = 1
AND TE.FL_ATIVO = 1
AND QE.FL_ATIVO = 1
AND QE.TX_PROTOCOLO is Not Null
AND QE.CEA_QUESTIONARIO = @CEA_QUESTIONARIO
AND TE.CEA_TURMA = @CEA_TURMA
------------------------------FILTROS DE TELA------------------------------
AND EC.TX_RAZAO_SOCIAL like '%' + @sRAZAO_SOCIAL + '%'
AND EC.TX_NOME_FANTASIA like '%' + @sNOME_FANTASIA + '%'
AND TE.CEA_ESTADO = COALESCE(@CEA_ESTADO, TE.CEA_ESTADO)
AND TE.CEA_CATEGORIA = COALESCE(@CEA_CATEGORIA, TE.CEA_CATEGORIA)
AND TE.CEA_NIVEL_ESCOLARIDADE = COALESCE(@CEA_NIVEL_ESCOLARIDADE, TE.CEA_NIVEL_ESCOLARIDADE )
AND TE.CEA_FAIXA_ETARIA = COALESCE(@CEA_FAIXA_ETARIA, TE.CEA_FAIXA_ETARIA)
AND TE.CEA_CIDADE = COALESCE(@CEA_CIDADE, TE.CEA_CIDADE)
AND ISNULL(ER.CDA_ESCRITORIO_REGIONAL, 0) = COALESCE(@CEA_ESCRITORIO_REGIONAL, ISNULL(ER.CDA_ESCRITORIO_REGIONAL, 0))
AND ISNULL(TE.STATUS, 0) = COALESCE(@STATUS, ISNULL(TE.STATUS, 0))
AND ISNULL(GE.CEA_GRUPO, 0) = COALESCE(@CEA_GRUPO, ISNULL(GE.CEA_GRUPO, 0))
AND ISNULL(TE.CEA_FATURAMENTO, 0) = COALESCE(@CEA_FATURAMENTO, ISNULL(TE.CEA_FATURAMENTO, 0))
AND ISNULL(QE.TX_PROTOCOLO, '') like '%' + @PROTOCOLO + '%'
AND EC.TX_CPF_CNPJ like '%' + @CPF_CNPJ + '%'
AND ISNULL(ESR.CDA_ESTADO_REGIAO, 0) = COALESCE(@CEA_ESTADO_REGIAO, ISNULL(ESR.CDA_ESTADO_REGIAO, 0))
AND ISNULL(TE.TX_SEXO_CONTATO, 0) = COALESCE(@TX_SEXO_CONTATO, ISNULL(TE.TX_SEXO_CONTATO, 0))
AND TE.DT_ULTIMA_ALTERACAO BETWEEN @DATAINICIO AND @DATAFIM
AND ISNULL(TE.NU_FUNCIONARIO, 0) = COALESCE(@NU_FUNCIONARIOS, ISNULL(TE.NU_FUNCIONARIO, 0))
AND ISNULL(TE.CEA_TIPO_EMPRESA, 0) =  COALESCE(@TIPO_EMPRESA, ISNULL(TE.CEA_TIPO_EMPRESA, 0))
-----------------------------------------------------------------------------
ORDER BY PontuacaoTotal DESC


RETURN  
END  
    
--
