SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[STP_DeletaQuestionarioPontuacaoPorIdQuestionarioEmpresa]
(
 @nCEA_QUESTIONARIO_EMPRESA int
)
As  
BEGIN   

SET NOCOUNT ON
	
	DELETE FROM TBL_QUESTIONARIO_PONTUACAO WHERE CEA_QUESTIONARIO_EMPRESA = @nCEA_QUESTIONARIO_EMPRESA;
	
RETURN
END
