alter PROCEDURE [dbo].STP_SelecionaRespostasDesempenhoGlobal  
(  
 @nIdPergunta INT  
)  
As      
BEGIN       
SET NOCOUNT ON    
  
 SELECT (SELECT COUNT(pr.LBL_RESPOSTA) TOTAL 
	       FROM TBL_PERGUNTA_RESPOSTA pr
	      INNER JOIN TBL_QUESTIONARIO_EMPRESA_RESPOSTA tqer ON tqer.CEA_RESPOSTA = pr.CDA_RESPOSTA
	      WHERE pr.CEA_PERGUNTA = @nIdPergunta) TOTAL,
        COUNT(pr.LBL_RESPOSTA) PARCIAL, 
        pr.LBL_RESPOSTA LBL_RESPOSTA
   FROM TBL_PERGUNTA_RESPOSTA pr
  INNER JOIN TBL_QUESTIONARIO_EMPRESA_RESPOSTA tqer ON tqer.CEA_RESPOSTA = pr.CDA_RESPOSTA
  WHERE pr.CEA_PERGUNTA = @nIdPergunta
  GROUP BY pr.LBL_RESPOSTA
    
RETURN    
END    
      
--  