USE [Sistema Gestao]
GO
/****** Object:  StoredProcedure [dbo].[STP_SelecionaProximaPerguntaPorQuestionarioEmpresa]    Script Date: 01/12/2011 14:18:19 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [dbo].[STP_SelecionaProximaPerguntaPorQuestionarioEmpresa]
(
 @nCEA_QUESTIONARIO_EMPRESA INT
)
As    
BEGIN     
SET NOCOUNT ON  

	SELECT p.CDA_PERGUNTA,
		   p.CEA_CRITERIO,
		   p.CEA_PERGUNTA_TIPO,
		   p.FL_ATIVO,
		   p.NU_ORDEM,
		   p.TX_GLOSSARIO,
		   p.TX_PERGUNTA,
		   p.TX_SAIBA_MAIS
	  FROM TBL_PERGUNTA p
 LEFT JOIN (SELECT * FROM TBL_QUESTIONARIO_EMPRESA_RESPOSTA WHERE CEA_QUESTIONARIO_EMPRESA = @nCEA_QUESTIONARIO_EMPRESA) qer ON qer.CEA_PERGUNTA = p.CDA_PERGUNTA
INNER JOIN TBL_QUESTIONARIO_EMPRESA qe ON qe.CDA_QUESTIONARIO_EMPRESA = @nCEA_QUESTIONARIO_EMPRESA
INNER JOIN TBL_CRITERIO c ON c.CDA_CRITERIO = p.CEA_CRITERIO AND c.CEA_QUESTIONARIO = qe.CEA_QUESTIONARIO
	 WHERE qer.CEA_QUESTIONARIO_EMPRESA IS NULL
  ORDER BY p.NU_ORDEM
  
RETURN  
END  
    
--    
