
/*   
------------------------------------------------------------------------------------------      
Procedure...............: STP_SelecionaEmpresasInscritasDigitadorPorFiltro
Funcao..................:  
  
  
Tabelas utilizadas......: 
Procedures utilizadas ..:   
Criada por..............: Robinson Campos
Data criacao............: 29/01/2011
Parmetros..............:   
    
Data  Nome   Descricao   
---------- ---------------- --------------------------------------------------   
dd/mm/aaaa XXXXXXXX   Alterao de parmetros   

---------- ---------------- --------------------------------------------------   
*/    

DECLARE @NAME_PROCEDURE VARCHAR(250) = 'STP_SelecionaEmpresasInscritasDigitadorPorFiltro'

IF NOT EXISTS (SELECT * FROM SYSOBJECTS WHERE ID = OBJECT_ID(@NAME_PROCEDURE) and sysstat & 0xf = 4)
BEGIN
  EXEC ('CREATE PROCEDURE [dbo].['+ @NAME_PROCEDURE +'] AS')
END
GO

ALTER PROCEDURE [dbo].STP_SelecionaEmpresasInscritasDigitadorPorFiltro
	@CEA_TIPO_ETAPA INT,
	@CEA_TURMA INT,    
	@sNOME_FANTASIA VARCHAR(500),    
	@CEA_ESTADO INT,    
	@CEA_CATEGORIA INT,    
	@CEA_NIVEL_ESCOLARIDADE INT,    
	@CEA_FAIXA_ETARIA INT,    
	@CEA_CIDADE INT,    
	@CEA_ESCRITORIO_REGIONAL INT,
	@CEA_GRUPO INT,    
	@CEA_FATURAMENTO INT,    
	@PROTOCOLO VARCHAR(200),    
	@CPF_CNPJ VARCHAR(200),    
	@CEA_ESTADO_REGIAO INT,    
	@TX_SEXO_CONTATO VARCHAR(1),    
	@DATAINICIO DATETIME,    
	@DATAFIM DATETIME,    
	@NU_FUNCIONARIOS INT,    
	@TIPO_EMPRESA INT,
	@CEA_QUESTIONARIO_RESPONSABILIDADE_SOCIAL INT,
	@CEA_QUESTIONARIO_INOVACAO INT,
	@FL_QUESTIONARIO_INOVACAO BIT,
	@FL_QUESTIONARIO_RESP_SOCIAL BIT,
	@FL_ATIVO BIT
As    
BEGIN     

SET NOCOUNT ON  
	
	SELECT DISTINCT    
		CAT.CDA_CATEGORIA,
		CAT.TX_CATEGORIA,
		TE.CEA_ESTADO,
		COUNT(DISTINCT CAD.CDA_EMP_CADASTRO) [QTD]
	FROM    
		TBL_EMP_CADASTRO CAD    
			JOIN TBL_TURMA_EMP TE ON TE.CEA_EMP_CADASTRO = CAD.CDA_EMP_CADASTRO     
			JOIN TBL_TURMA T ON TE.CEA_TURMA = T.CDA_TURMA
			JOIN TBL_CATEGORIA CAT ON CAT.CDA_CATEGORIA = TE.CEA_CATEGORIA    
			JOIN TBL_CIDADE C ON C.CDA_CIDADE = TE.CEA_CIDADE
			JOIN TBL_CARGO CA ON CA.CDA_CARGO = TE.CEA_CARGO          
			JOIN TBL_BAIRRO BA ON BA.CDA_BAIRRO = TE.CEA_BAIRRO  
			JOIN TBL_CIDADE CI ON CI.CDA_CIDADE = TE.CEA_CIDADE  
			JOIN TBL_ESTADO ES ON ES.CDA_ESTADO = TE.CEA_ESTADO  
			JOIN TBL_TIPO_EMP TI ON TI.CDA_TIPO_EMPRESA = TE.CEA_TIPO_EMPRESA  
			JOIN TBL_FATURAMENTO FA ON FA.CDA_FATURAMENTO = TE.CEA_FATURAMENTO  
			JOIN TBL_ATIVIDADE_ECONOMICA AE ON AE.CDA_ATIVIDADE_ECONOMICA = TE.CEA_ATIVIDADE_ECONOMICA  
			JOIN TBL_CONTATO_NIVEL_ESCOLARIDADE NE ON NE.CDA_NIVEL_ESCOLARIDADE = TE.CEA_NIVEL_ESCOLARIDADE  
			JOIN TBL_CONTATO_FAIXA_ETARIA FE ON FE.CDA_FAIXA_ETARIA = TE.CEA_FAIXA_ETARIA  
			JOIN TBL_ESTADO_REGIAO ESR ON ESR.CDA_ESTADO_REGIAO = ES.CDA_ESTADO  
			LEFT JOIN TBL_ESCRITORIO_REGIONAL ER ON ER.CEA_ESTADO = ES.CDA_ESTADO  
			LEFT JOIN TBL_GRUPOEMPRESA GE ON GE.CEA_EMP_CADASTRO = CAD.CDA_EMP_CADASTRO  
			LEFT JOIN TBL_QUESTIONARIO_EMPRESA QE ON T.CEA_PROGRAMA = QE.CEA_PROGRAMA AND QE.CEA_EMP_CADASTRO = CAD.CDA_EMP_CADASTRO
	WHERE
		TE.CEA_USUARIO IS NOT NULL AND TE.CEA_USUARIO <> 0
		AND TE.FL_ATIVO = 1 
		AND QE.FL_ATIVO = @FL_ATIVO
		AND T.CDA_TURMA = @CEA_TURMA
		AND ISNULL(TE.CEA_ESTADO, 0) = COALESCE(@CEA_ESTADO, ISNULL(TE.CEA_ESTADO, 0))    
		AND CAD.TX_NOME_FANTASIA like '%' + @sNOME_FANTASIA + '%'
		AND ISNULL(TE.CEA_CATEGORIA, 0) = COALESCE(@CEA_CATEGORIA, ISNULL(TE.CEA_CATEGORIA, 0))    
		AND ISNULL(TE.CEA_NIVEL_ESCOLARIDADE, 0) = COALESCE(@CEA_NIVEL_ESCOLARIDADE, ISNULL(TE.CEA_NIVEL_ESCOLARIDADE, 0))    
		AND ISNULL(TE.CEA_FAIXA_ETARIA, 0) = COALESCE(@CEA_FAIXA_ETARIA, ISNULL(TE.CEA_FAIXA_ETARIA, 0))    
		AND ISNULL(TE.CEA_CIDADE, 0) = COALESCE(@CEA_CIDADE, ISNULL(TE.CEA_CIDADE, 0))    
		AND ISNULL(ER.CDA_ESCRITORIO_REGIONAL, 0) = COALESCE(@CEA_ESCRITORIO_REGIONAL, ISNULL(ER.CDA_ESCRITORIO_REGIONAL, 0))    
		AND ISNULL(GE.CEA_GRUPO, 0) = COALESCE(@CEA_GRUPO, ISNULL(GE.CEA_GRUPO, 0))    
		AND ISNULL(TE.CEA_FATURAMENTO, 0) = COALESCE(@CEA_FATURAMENTO, ISNULL(TE.CEA_FATURAMENTO, 0))    
		AND ISNULL(QE.TX_PROTOCOLO, '') like '%' + @PROTOCOLO + '%'    
		AND CAD.TX_CPF_CNPJ like '%' + @CPF_CNPJ + '%'    
		AND ISNULL(ESR.CDA_ESTADO_REGIAO, 0) = COALESCE(@CEA_ESTADO_REGIAO, ISNULL(ESR.CDA_ESTADO_REGIAO, 0))    
		AND ISNULL(TE.TX_SEXO_CONTATO, 0) = COALESCE(@TX_SEXO_CONTATO, ISNULL(TE.TX_SEXO_CONTATO, 0))    
		AND TE.DT_ULTIMA_ALTERACAO BETWEEN @DATAINICIO AND @DATAFIM    
		AND ISNULL(TE.NU_FUNCIONARIO, 0) = COALESCE(@NU_FUNCIONARIOS, ISNULL(TE.NU_FUNCIONARIO, 0))    
		AND ISNULL(TE.CEA_TIPO_EMPRESA, 0) = COALESCE(@TIPO_EMPRESA, ISNULL(TE.CEA_TIPO_EMPRESA, 0))
		--Possui Questionário de Responsabilidade Social----------       
		AND (@FL_QUESTIONARIO_RESP_SOCIAL = CASE  WHEN @FL_QUESTIONARIO_RESP_SOCIAL = 1 THEN ISNULL((SELECT TOP 1 1 FROM TBL_QUESTIONARIO_EMPRESA QRESP WHERE QRESP.CEA_EMP_CADASTRO = CAD.CDA_EMP_CADASTRO AND QRESP.FL_ATIVO = @FL_ATIVO AND QRESP.CEA_QUESTIONARIO = @CEA_QUESTIONARIO_RESPONSABILIDADE_SOCIAL), 0) ELSE 0 END
		----------------------------------------------------------
		--Possui do Questionário de Inovação------------        
		OR @FL_QUESTIONARIO_INOVACAO = CASE  WHEN @FL_QUESTIONARIO_RESP_SOCIAL = 1 THEN ISNULL((SELECT TOP 1 1 FROM TBL_QUESTIONARIO_EMPRESA QINOVA WHERE QINOVA.CEA_EMP_CADASTRO = CAD.CDA_EMP_CADASTRO AND QINOVA.FL_ATIVO = @FL_ATIVO AND QINOVA.CEA_QUESTIONARIO = @CEA_QUESTIONARIO_INOVACAO), 0) ELSE 0 END)
		------------------------------------------------
	GROUP BY    
		CAT.CDA_CATEGORIA,    
		CAT.TX_CATEGORIA,    
		TE.CEA_ESTADO    
			
RETURN  

END  
    
--    
