SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[STP_AtualizaQuestionarioEmpresaInsereDevolucao]
    @nCDA_QUESTIONARIO_EMPRESA INT,
	@TX_RESUMO NTEXT
	
As  
BEGIN   

SET NOCOUNT ON

UPDATE [TBL_QUESTIONARIO_EMPRESA]
   SET FL_PARA_AVALIACAO = 'False', FL_EXCLUIDO = 'False'
 WHERE CDA_QUESTIONARIO_EMPRESA = @nCDA_QUESTIONARIO_EMPRESA

UPDATE [TBL_QUESTIONARIO_EMPRESA_AVALIADOR]
   SET TX_BANCA = @TX_RESUMO
 WHERE CEA_QUESTIONARIO_EMPRESA = @nCDA_QUESTIONARIO_EMPRESA


RETURN
END
