/*   
------------------------------------------------------------------------------------------   
Procedure...............: STP_RankingEstadualPorTipoEtapaFiltros
Funcao..................:  
  
  
Tabelas utilizadas......: TBL_QUESTIONARIO_EMPRESA, TBL_TURMA_EMPRESA, TBL_QUESTIONARIO_PONTUACAO
Procedures utilizadas ..:   
Criada por..............: Fabio Moraes
Data criacao............: 16/01/2011
Parmetros..............:   
    
Data  Nome   Descricao   
---------- ---------------- --------------------------------------------------   
dd/mm/aaaa XXXXXXXX   Alterao de parmetros   

---------- ---------------- --------------------------------------------------   
*/    
DECLARE @NAME_PROCEDURE VARCHAR(250) = 'STP_RankingEstadualPorTipoEtapaFiltros'

IF NOT EXISTS (SELECT * FROM SYSOBJECTS WHERE ID = OBJECT_ID(@NAME_PROCEDURE) and sysstat & 0xf = 4)
BEGIN
  EXEC ('CREATE PROCEDURE [dbo].['+ @NAME_PROCEDURE +'] AS')
END
GO


ALTER PROCEDURE [dbo].STP_RankingEstadualPorTipoEtapaFiltros
(
@CEA_TIPO_ETAPA INT,
@CEA_TIPO_ETAPA_FINAL INT,
@CEA_TURMA INT,
----------CRITERIOS GESTÃO--------------------
@CEA_CRITERIO_CLIENTE INT,
@CEA_CRITERIO_SOCIEDADE INT,
@CEA_CRITERIO_LIDERANCA INT,
@CEA_CRITERIO_ESTRATEGIA_PLANO INT,
@CEA_CRITERIO_PESSOAS INT,
@CEA_CRITERIO_PROCESSOS INT,
@CEA_CRITERIO_INFORMACAO_CONHECIMENTO INT,
@CEA_CRITERIO_RESULTADO_CONTROLE INT,
@CEA_CRITERIO_RESULTADO_TENDENCIA INT,
------------------------------------------
-------QUESTIONARIOS----------------------
@CEA_QUESTIONARIO_GESTAO INT,
@CEA_QUESTIONARIO_INOVACAO INT,
@CEA_QUESTIONARIO_EMPREENDEDORISMO INT,
@CEA_QUESTIONARIO_RESPONSABILIDADE_SOCIAL INT,
--------FILTROS DE TELA-------------------
@sNOME_FANTASIA VARCHAR(500),
@CEA_ESTADO INT,
@CEA_CATEGORIA INT,
@CEA_NIVEL_ESCOLARIDADE INT,
@CEA_FAIXA_ETARIA INT,
@CEA_CIDADE INT,
@CEA_ESCRITORIO_REGIONAL INT,
@STATUS INT,
@CEA_GRUPO INT,
@CEA_FATURAMENTO INT,
@PROTOCOLO VARCHAR(200),
@CPF_CNPJ VARCHAR(200),
@CEA_ESTADO_REGIAO INT,
@TX_SEXO_CONTATO VARCHAR(1),
@DATAINICIO DATETIME,
@DATAFIM DATETIME,
@NU_FUNCIONARIOS INT,
@TIPO_EMPRESA INT
------------------------------------------
)
As   
BEGIN     

SET NOCOUNT ON  

--Considera Respostas do Avaliador
DECLARE @bIS_AVALIADOR BIT
SET @bIS_AVALIADOR = 1
---------------------------------
--Considera Repostas da Empresa
DECLARE @bIS_EMPRESA BIT
SET @bIS_EMPRESA = 1
---------------------------------

SELECT
EC.CDA_EMP_CADASTRO,
QE.CDA_QUESTIONARIO_EMPRESA,
EC.TX_CPF_CNPJ,
EC.TX_RAZAO_SOCIAL,
--Possui Questionário de Responsabilidade Social----------       
ISNULL((SELECT QRESP.CDA_QUESTIONARIO_EMPRESA FROM TBL_QUESTIONARIO_EMPRESA QRESP WHERE QRESP.CEA_EMP_CADASTRO = EC.CDA_EMP_CADASTRO AND QRESP.FL_ATIVO = 1 AND QRESP.CEA_QUESTIONARIO = @CEA_QUESTIONARIO_RESPONSABILIDADE_SOCIAL AND QE.TX_PROTOCOLO is Not Null), 0) [PossuiResponsabilidadeSocial],
----------------------------------------------------------
--Possui do Questionário de Inovação------------        
ISNULL((SELECT QINOVA.CDA_QUESTIONARIO_EMPRESA FROM TBL_QUESTIONARIO_EMPRESA QINOVA WHERE QINOVA.CEA_EMP_CADASTRO = EC.CDA_EMP_CADASTRO AND QINOVA.FL_ATIVO = 1 AND QINOVA.CEA_QUESTIONARIO = @CEA_QUESTIONARIO_INOVACAO AND QE.TX_PROTOCOLO is Not Null), 0) [PossuiInovacao],
------------------------------------------------
--Verifica se a Empresa é Finalista do Questionário de Responsabilidade Social----------       
ISNULL((SELECT QFINAL.CDA_QUESTIONARIO_EMPRESA FROM TBL_QUESTIONARIO_EMPRESA QFINAL 
		JOIN TBL_ETAPA ETFINAL ON ETFINAL.CDA_ETAPA = QFINAL.CEA_ETAPA
		JOIN TBL_TIPO_ETAPA TIEFINAL ON TIEFINAL.CDA_TIPO_ETAPA = ETFINAL.CEA_TIPO_ETAPA 
		WHERE ET.CEA_TIPO_ETAPA = @CEA_TIPO_ETAPA_FINAL 
		AND QFINAL.CEA_EMP_CADASTRO = EC.CDA_EMP_CADASTRO 
		AND QFINAL.FL_ATIVO = 1 
		AND QFINAL.CEA_QUESTIONARIO = @CEA_QUESTIONARIO_RESPONSABILIDADE_SOCIAL 
		AND QE.TX_PROTOCOLO is Not Null), 0) [FinalistaResponsabilidadeSocial],
----------------------------------------------------------
--Verifica se a Empresa é Finalista do Questionário de Inovação------------        
ISNULL((SELECT QFINAL.CDA_QUESTIONARIO_EMPRESA FROM TBL_QUESTIONARIO_EMPRESA QFINAL 
		JOIN TBL_ETAPA ETFINAL ON ETFINAL.CDA_ETAPA = QFINAL.CEA_ETAPA
		JOIN TBL_TIPO_ETAPA TIEFINAL ON TIEFINAL.CDA_TIPO_ETAPA = ETFINAL.CEA_TIPO_ETAPA 
		WHERE ET.CEA_TIPO_ETAPA = @CEA_TIPO_ETAPA_FINAL 
		AND QFINAL.CEA_EMP_CADASTRO = EC.CDA_EMP_CADASTRO 
		AND QFINAL.FL_ATIVO = 1 
		AND QFINAL.CEA_QUESTIONARIO = @CEA_QUESTIONARIO_INOVACAO 
		AND QE.TX_PROTOCOLO is Not Null), 0) [FinalistaInovacao],
------------------------------------------------
--Verifica se a Empresa é Finalista---------        
ISNULL((SELECT QFINAL.CDA_QUESTIONARIO_EMPRESA FROM TBL_QUESTIONARIO_EMPRESA QFINAL 
		JOIN TBL_ETAPA ETFINAL ON ETFINAL.CDA_ETAPA = QFINAL.CEA_ETAPA
		JOIN TBL_TIPO_ETAPA TIEFINAL ON TIEFINAL.CDA_TIPO_ETAPA = ETFINAL.CEA_TIPO_ETAPA 
		WHERE ET.CEA_TIPO_ETAPA = @CEA_TIPO_ETAPA_FINAL 
		AND QFINAL.CEA_EMP_CADASTRO = EC.CDA_EMP_CADASTRO 
		AND QFINAL.FL_ATIVO = 1 
		AND QFINAL.CEA_QUESTIONARIO = @CEA_QUESTIONARIO_GESTAO 
		AND QE.TX_PROTOCOLO is Not Null), 0) [Finalista],
------------------------------------------------------------------------
------------------------POS-VISITA--------------------------------------
ISNULL(P1, 0) + ISNULL(P2, 0) + ISNULL(P3, 0) + ISNULL(P4, 0) + ISNULL(P5, 0) + ISNULL(P6, 0) + ISNULL(P7, 0) + ISNULL(P8, 0) + ISNULL(P9, 0) [PontuacaoTotalPosVisita],
ISNULL(P1, 0) + ISNULL(P2, 0) + ISNULL(P3, 0) + ISNULL(P4, 0) + ISNULL(P5, 0) + ISNULL(P6, 0) + ISNULL(P7, 0)  [TotalEnfoquePosVisita],
ISNULL(P8, 0)  [ResultadoControlePosVisita],
ISNULL(P9, 0)  [ResultadoTendenciaPosVisita],
--Pontuação do Questionário de Empreendedorismo----        
ISNULL((SELECT QEMP.NU_TOTAL_PONTUACAO_AVALIADOR FROM TBL_QUESTIONARIO_EMPRESA QEMP WHERE QEMP.CEA_EMP_CADASTRO = EC.CDA_EMP_CADASTRO AND QEMP.FL_ATIVO = 1 AND QEMP.CEA_QUESTIONARIO = @CEA_QUESTIONARIO_EMPREENDEDORISMO AND QE.TX_PROTOCOLO is Not Null), 0) [TotalEmpreendedorismoPosVisita],
---------------------------------------------------
--------Relação com a Melhor da Categoria-------
--,((QE.NU_TOTAL_PONTUACAO_AVALIADOR * 100)/(SELECT MAX(QGESTAO.NU_TOTAL_PONTUACAO_AVALIADOR) FROM TBL_QUESTIONARIO_EMPRESA QGESTAO WHERE QGESTAO.CEA_EMP_CADASTRO = EC.CDA_EMP_CADASTRO AND QGESTAO.FL_ATIVO = 1 AND QGESTAO.CEA_QUESTIONARIO = @CEA_QUESTIONARIO_GESTAO AND QE.TX_PROTOCOLO is Not Null))
'0.0' [RelacaoComMelhorDaCategoriaPosVisita],
------------------------------------------------------------------------
------------------------PRE-VISITA--------------------------------------
ISNULL(P10, 0) + ISNULL(P11, 0) + ISNULL(P12, 0) + ISNULL(P13, 0) + ISNULL(P14, 0) + ISNULL(P15, 0) + ISNULL(P16, 0) + ISNULL(P17, 0) [PontuacaoRankingPreVisita],
ISNULL(P10, 0) + ISNULL(P11, 0) + ISNULL(P12, 0) + ISNULL(P13, 0) + ISNULL(P14, 0) + ISNULL(P15, 0) + ISNULL(P16, 0) + ISNULL(P17, 0) + ISNULL(P18, 0) [PontuacaoTotalPreVisita],
ISNULL(P10, 0) + ISNULL(P11, 0) + ISNULL(P12, 0) + ISNULL(P13, 0) + ISNULL(P14, 0) + ISNULL(P15, 0) + ISNULL(P16, 0) [TotalEnfoquePreVisita],
ISNULL(P17, 0) [ResultadoControlePreVisita],
ISNULL(P18, 0) [ResultadoTendenciaPreVisita],
--------Relação com a Melhor da Categoria-------
--,((QE.NU_TOTAL_PONTUACAO * 100)/(SELECT MAX(QGESTAO.NU_TOTAL_PONTUACAO) FROM TBL_QUESTIONARIO_EMPRESA QGESTAO WHERE QGESTAO.CEA_EMP_CADASTRO = EC.CDA_EMP_CADASTRO AND QGESTAO.FL_ATIVO = 1 AND QGESTAO.CEA_QUESTIONARIO = @CEA_QUESTIONARIO_GESTAO AND QE.TX_PROTOCOLO is Not Null))
'0.0' [RelacaoComMelhorDaCategoriaPreVisita]
------------------------------------------------------------------------
FROM TBL_TURMA_EMP TE
JOIN TBL_EMP_CADASTRO EC ON EC.CDA_EMP_CADASTRO = TE.CEA_EMP_CADASTRO
JOIN TBL_QUESTIONARIO_EMPRESA QE ON QE.CEA_EMP_CADASTRO = TE.CEA_EMP_CADASTRO
JOIN TBL_ETAPA ET ON ET.CDA_ETAPA = QE.CEA_ETAPA
JOIN TBL_TIPO_ETAPA TIE ON TIE.CDA_TIPO_ETAPA = ET.CEA_TIPO_ETAPA
------------------------POS-VISITA--------------------------------------
--Critério Cliente--
LEFT JOIN (  SELECT SUM(NU_PONTO) AS P1, CEA_CRITERIO, CEA_QUESTIONARIO_EMPRESA, FL_AVALIADOR    
       FROM  TBL_QUESTIONARIO_PONTUACAO      
       WHERE CEA_CRITERIO = @CEA_CRITERIO_CLIENTE AND FL_AVALIADOR = COALESCE(@bIS_AVALIADOR, FL_AVALIADOR)  
       GROUP BY CEA_QUESTIONARIO_EMPRESA, CEA_CRITERIO, FL_AVALIADOR) QP1     
       ON QP1.CEA_QUESTIONARIO_EMPRESA = QE.CEA_QUESTIONARIO_EMPRESA_PAI
----------------------
--Critério Sociedade--
LEFT JOIN (  SELECT SUM(NU_PONTO) AS P2, CEA_CRITERIO, CEA_QUESTIONARIO_EMPRESA    
       FROM TBL_QUESTIONARIO_PONTUACAO     
       WHERE CEA_CRITERIO = @CEA_CRITERIO_SOCIEDADE AND FL_AVALIADOR = COALESCE(@bIS_AVALIADOR, FL_AVALIADOR)  
       GROUP BY CEA_QUESTIONARIO_EMPRESA, CEA_CRITERIO, FL_AVALIADOR) QP2     
       ON QP2.CEA_QUESTIONARIO_EMPRESA = QE.CEA_QUESTIONARIO_EMPRESA_PAI
----------------------
--Critério Liderança--
LEFT JOIN (  SELECT SUM(NU_PONTO) AS P3, CEA_CRITERIO, CEA_QUESTIONARIO_EMPRESA    
       FROM TBL_QUESTIONARIO_PONTUACAO     
       WHERE CEA_CRITERIO = @CEA_CRITERIO_LIDERANCA AND FL_AVALIADOR = COALESCE(@bIS_AVALIADOR, FL_AVALIADOR)  
       GROUP BY CEA_QUESTIONARIO_EMPRESA, CEA_CRITERIO, FL_AVALIADOR) QP3     
       ON QP3.CEA_QUESTIONARIO_EMPRESA = QE.CEA_QUESTIONARIO_EMPRESA_PAI 
----------------------         
--Critério Estrategia e Planos--
LEFT JOIN (  SELECT SUM(NU_PONTO) AS P4, CEA_CRITERIO, CEA_QUESTIONARIO_EMPRESA    
       FROM TBL_QUESTIONARIO_PONTUACAO     
       WHERE CEA_CRITERIO = @CEA_CRITERIO_ESTRATEGIA_PLANO AND FL_AVALIADOR = COALESCE(@bIS_AVALIADOR, FL_AVALIADOR)  
       GROUP BY CEA_QUESTIONARIO_EMPRESA, CEA_CRITERIO, FL_AVALIADOR) QP4     
       ON QP4.CEA_QUESTIONARIO_EMPRESA = QE.CEA_QUESTIONARIO_EMPRESA_PAI 
----------------------
--Critério Pessoas--
LEFT JOIN (  SELECT SUM(NU_PONTO) AS P5, CEA_CRITERIO, CEA_QUESTIONARIO_EMPRESA    
       FROM TBL_QUESTIONARIO_PONTUACAO     
       WHERE CEA_CRITERIO = @CEA_CRITERIO_PESSOAS AND FL_AVALIADOR = COALESCE(@bIS_AVALIADOR, FL_AVALIADOR)  
       GROUP BY CEA_QUESTIONARIO_EMPRESA, CEA_CRITERIO, FL_AVALIADOR) QP5     
       ON QP5.CEA_QUESTIONARIO_EMPRESA = QE.CEA_QUESTIONARIO_EMPRESA_PAI 
----------------------    
--Critério Processos--
   LEFT JOIN (  SELECT SUM(NU_PONTO) AS P6, CEA_CRITERIO, CEA_QUESTIONARIO_EMPRESA    
       FROM TBL_QUESTIONARIO_PONTUACAO     
       WHERE CEA_CRITERIO = @CEA_CRITERIO_PROCESSOS AND FL_AVALIADOR = COALESCE(@bIS_AVALIADOR, FL_AVALIADOR)  
       GROUP BY CEA_QUESTIONARIO_EMPRESA, CEA_CRITERIO, FL_AVALIADOR) QP6     
       ON QP6.CEA_QUESTIONARIO_EMPRESA = QE.CEA_QUESTIONARIO_EMPRESA_PAI   
----------------------
--Critério Informações e Conhecimento-         
   LEFT JOIN (  SELECT SUM(NU_PONTO) AS P7, CEA_CRITERIO, CEA_QUESTIONARIO_EMPRESA    
       FROM TBL_QUESTIONARIO_PONTUACAO     
       WHERE CEA_CRITERIO = @CEA_CRITERIO_INFORMACAO_CONHECIMENTO AND FL_AVALIADOR = COALESCE(@bIS_AVALIADOR, FL_AVALIADOR)  
       GROUP BY CEA_QUESTIONARIO_EMPRESA, CEA_CRITERIO, FL_AVALIADOR) QP7     
       ON QP7.CEA_QUESTIONARIO_EMPRESA = QE.CEA_QUESTIONARIO_EMPRESA_PAI     
----------------------
--Critério Resultado de Controle--       
   LEFT JOIN (  SELECT SUM(NU_PONTO) AS P8, CEA_CRITERIO, CEA_QUESTIONARIO_EMPRESA    
       FROM TBL_QUESTIONARIO_PONTUACAO     
       WHERE CEA_CRITERIO = @CEA_CRITERIO_RESULTADO_CONTROLE AND FL_AVALIADOR = COALESCE(@bIS_AVALIADOR, FL_AVALIADOR)  
       GROUP BY CEA_QUESTIONARIO_EMPRESA, CEA_CRITERIO, FL_AVALIADOR) QP8     
       ON QP8.CEA_QUESTIONARIO_EMPRESA = QE.CEA_QUESTIONARIO_EMPRESA_PAI     
----------------------
--Critério Resultado de Tendência--        
   LEFT JOIN (  SELECT SUM(NU_PONTO) AS P9, CEA_CRITERIO, CEA_QUESTIONARIO_EMPRESA    
       FROM TBL_QUESTIONARIO_PONTUACAO     
       WHERE CEA_CRITERIO = @CEA_CRITERIO_RESULTADO_TENDENCIA AND FL_AVALIADOR = COALESCE(@bIS_AVALIADOR, FL_AVALIADOR)  
       GROUP BY CEA_QUESTIONARIO_EMPRESA, CEA_CRITERIO, FL_AVALIADOR) QP9     
       ON QP9.CEA_QUESTIONARIO_EMPRESA = QE.CEA_QUESTIONARIO_EMPRESA_PAI           
------------------------------------------------------------------------
------------------------PRE-VISITA--------------------------------------
--Critério Cliente--
LEFT JOIN (  SELECT SUM(NU_PONTO) AS P10, CEA_CRITERIO, CEA_QUESTIONARIO_EMPRESA, FL_AVALIADOR    
       FROM  TBL_QUESTIONARIO_PONTUACAO      
       WHERE CEA_CRITERIO = @CEA_CRITERIO_CLIENTE AND FL_AVALIADOR = COALESCE(@bIS_EMPRESA, FL_AVALIADOR)  
       GROUP BY CEA_QUESTIONARIO_EMPRESA, CEA_CRITERIO, FL_AVALIADOR) QP10     
       ON QP10.CEA_QUESTIONARIO_EMPRESA = QE.CEA_QUESTIONARIO_EMPRESA_PAI
----------------------
--Critério Sociedade--
LEFT JOIN (  SELECT SUM(NU_PONTO) AS P11, CEA_CRITERIO, CEA_QUESTIONARIO_EMPRESA    
       FROM TBL_QUESTIONARIO_PONTUACAO     
       WHERE CEA_CRITERIO = @CEA_CRITERIO_SOCIEDADE AND FL_AVALIADOR = COALESCE(@bIS_EMPRESA, FL_AVALIADOR)  
       GROUP BY CEA_QUESTIONARIO_EMPRESA, CEA_CRITERIO, FL_AVALIADOR) QP11    
       ON QP11.CEA_QUESTIONARIO_EMPRESA = QE.CEA_QUESTIONARIO_EMPRESA_PAI
----------------------
--Critério Liderança--
LEFT JOIN (  SELECT SUM(NU_PONTO) AS P12, CEA_CRITERIO, CEA_QUESTIONARIO_EMPRESA    
       FROM TBL_QUESTIONARIO_PONTUACAO     
       WHERE CEA_CRITERIO = @CEA_CRITERIO_LIDERANCA AND FL_AVALIADOR = COALESCE(@bIS_EMPRESA, FL_AVALIADOR)  
       GROUP BY CEA_QUESTIONARIO_EMPRESA, CEA_CRITERIO, FL_AVALIADOR) QP12     
       ON QP12.CEA_QUESTIONARIO_EMPRESA = QE.CEA_QUESTIONARIO_EMPRESA_PAI 
----------------------         
--Critério Estrategia e Planos--
LEFT JOIN (  SELECT SUM(NU_PONTO) AS P13, CEA_CRITERIO, CEA_QUESTIONARIO_EMPRESA    
       FROM TBL_QUESTIONARIO_PONTUACAO     
       WHERE CEA_CRITERIO = @CEA_CRITERIO_ESTRATEGIA_PLANO AND FL_AVALIADOR = COALESCE(@bIS_EMPRESA, FL_AVALIADOR)  
       GROUP BY CEA_QUESTIONARIO_EMPRESA, CEA_CRITERIO, FL_AVALIADOR) QP13    
       ON QP13.CEA_QUESTIONARIO_EMPRESA = QE.CEA_QUESTIONARIO_EMPRESA_PAI 
----------------------
--Critério Pessoas--
LEFT JOIN (  SELECT SUM(NU_PONTO) AS P14, CEA_CRITERIO, CEA_QUESTIONARIO_EMPRESA    
       FROM TBL_QUESTIONARIO_PONTUACAO     
       WHERE CEA_CRITERIO = @CEA_CRITERIO_PESSOAS AND FL_AVALIADOR = COALESCE(@bIS_EMPRESA, FL_AVALIADOR)  
       GROUP BY CEA_QUESTIONARIO_EMPRESA, CEA_CRITERIO, FL_AVALIADOR) QP14     
       ON QP14.CEA_QUESTIONARIO_EMPRESA = QE.CEA_QUESTIONARIO_EMPRESA_PAI 
----------------------    
--Critério Processos--
   LEFT JOIN (  SELECT SUM(NU_PONTO) AS P15, CEA_CRITERIO, CEA_QUESTIONARIO_EMPRESA    
       FROM TBL_QUESTIONARIO_PONTUACAO     
       WHERE CEA_CRITERIO = @CEA_CRITERIO_PROCESSOS AND FL_AVALIADOR = COALESCE(@bIS_EMPRESA, FL_AVALIADOR)  
       GROUP BY CEA_QUESTIONARIO_EMPRESA, CEA_CRITERIO, FL_AVALIADOR) QP15     
       ON QP15.CEA_QUESTIONARIO_EMPRESA = QE.CEA_QUESTIONARIO_EMPRESA_PAI   
----------------------
--Critério Informações e Conhecimento-         
   LEFT JOIN (  SELECT SUM(NU_PONTO) AS P16, CEA_CRITERIO, CEA_QUESTIONARIO_EMPRESA    
       FROM TBL_QUESTIONARIO_PONTUACAO     
       WHERE CEA_CRITERIO = @CEA_CRITERIO_INFORMACAO_CONHECIMENTO AND FL_AVALIADOR = COALESCE(@bIS_EMPRESA, FL_AVALIADOR)  
       GROUP BY CEA_QUESTIONARIO_EMPRESA, CEA_CRITERIO, FL_AVALIADOR) QP16     
       ON QP16.CEA_QUESTIONARIO_EMPRESA = QE.CEA_QUESTIONARIO_EMPRESA_PAI     
----------------------
--Critério Resultado de Controle--       
   LEFT JOIN (  SELECT SUM(NU_PONTO) AS P17, CEA_CRITERIO, CEA_QUESTIONARIO_EMPRESA    
       FROM TBL_QUESTIONARIO_PONTUACAO     
       WHERE CEA_CRITERIO = @CEA_CRITERIO_RESULTADO_CONTROLE AND FL_AVALIADOR = COALESCE(@bIS_EMPRESA, FL_AVALIADOR)  
       GROUP BY CEA_QUESTIONARIO_EMPRESA, CEA_CRITERIO, FL_AVALIADOR) QP17     
       ON QP17.CEA_QUESTIONARIO_EMPRESA = QE.CEA_QUESTIONARIO_EMPRESA_PAI     
----------------------
--Critério Resultado de Tendência--        
   LEFT JOIN (  SELECT SUM(NU_PONTO) AS P18, CEA_CRITERIO, CEA_QUESTIONARIO_EMPRESA    
       FROM TBL_QUESTIONARIO_PONTUACAO     
       WHERE CEA_CRITERIO = @CEA_CRITERIO_RESULTADO_TENDENCIA AND FL_AVALIADOR = COALESCE(@bIS_EMPRESA, FL_AVALIADOR)  
       GROUP BY CEA_QUESTIONARIO_EMPRESA, CEA_CRITERIO, FL_AVALIADOR) QP18     
       ON QP18.CEA_QUESTIONARIO_EMPRESA = QE.CEA_QUESTIONARIO_EMPRESA_PAI  
------------------------------------------------------------------------ 
-----------FILTROS DE TELA----------------------------------------------
JOIN TBL_CARGO CA ON CA.CDA_CARGO = TE.CEA_CARGO        
JOIN TBL_BAIRRO BA ON BA.CDA_BAIRRO = TE.CEA_BAIRRO
JOIN TBL_CIDADE CI ON CI.CDA_CIDADE = TE.CEA_CIDADE
JOIN TBL_ESTADO ES ON ES.CDA_ESTADO = TE.CEA_ESTADO
JOIN TBL_TIPO_EMP TI ON TI.CDA_TIPO_EMPRESA = TE.CEA_TIPO_EMPRESA
JOIN TBL_FATURAMENTO FA ON FA.CDA_FATURAMENTO = TE.CEA_FATURAMENTO
JOIN TBL_CATEGORIA CAT ON CAT.CDA_CATEGORIA = TE.CEA_CATEGORIA
JOIN TBL_ATIVIDADE_ECONOMICA AE ON AE.CDA_ATIVIDADE_ECONOMICA = TE.CEA_ATIVIDADE_ECONOMICA
JOIN TBL_CONTATO_NIVEL_ESCOLARIDADE NE ON NE.CDA_NIVEL_ESCOLARIDADE = TE.CEA_NIVEL_ESCOLARIDADE
JOIN TBL_CONTATO_FAIXA_ETARIA FE ON FE.CDA_FAIXA_ETARIA = TE.CEA_FAIXA_ETARIA
LEFT JOIN TBL_ESCRITORIO_REGIONAL ER ON ER.CEA_ESTADO = ES.CDA_ESTADO
LEFT JOIN TBL_GRUPOEMPRESA GE ON GE.CEA_EMP_CADASTRO = EC.CDA_EMP_CADASTRO
JOIN TBL_ESTADO_REGIAO ESR ON ESR.CDA_ESTADO_REGIAO = ES.CDA_ESTADO
-----------------------------------------------------------------------------
WHERE ET.CEA_TIPO_ETAPA = @CEA_TIPO_ETAPA
AND EC.FL_ATIVO = 1
AND TE.FL_ATIVO = 1
AND QE.FL_ATIVO = 1
AND QE.TX_PROTOCOLO is Not Null
AND QE.CEA_QUESTIONARIO = @CEA_QUESTIONARIO_GESTAO
AND TE.CEA_TURMA = @CEA_TURMA
------------------------------FILTROS DE TELA------------------------------
AND EC.TX_NOME_FANTASIA like '%' + @sNOME_FANTASIA + '%'
AND TE.CEA_ESTADO = COALESCE(@CEA_ESTADO, TE.CEA_ESTADO)
AND TE.CEA_CATEGORIA = COALESCE(@CEA_CATEGORIA, TE.CEA_CATEGORIA)
AND TE.CEA_NIVEL_ESCOLARIDADE = COALESCE(@CEA_NIVEL_ESCOLARIDADE, TE.CEA_NIVEL_ESCOLARIDADE )
AND TE.CEA_FAIXA_ETARIA = COALESCE(@CEA_FAIXA_ETARIA, TE.CEA_FAIXA_ETARIA)
AND TE.CEA_CIDADE = COALESCE(@CEA_CIDADE, TE.CEA_CIDADE)
AND ISNULL(ER.CDA_ESCRITORIO_REGIONAL, 0) = COALESCE(@CEA_ESCRITORIO_REGIONAL, ISNULL(ER.CDA_ESCRITORIO_REGIONAL, 0))
AND ISNULL(TE.STATUS, 0) = COALESCE(@STATUS, ISNULL(TE.STATUS, 0))
AND ISNULL(GE.CEA_GRUPO, 0) = COALESCE(@CEA_GRUPO, ISNULL(GE.CEA_GRUPO, 0))
AND ISNULL(TE.CEA_FATURAMENTO, 0) = COALESCE(@CEA_FATURAMENTO, ISNULL(TE.CEA_FATURAMENTO, 0))
AND ISNULL(QE.TX_PROTOCOLO, '') like '%' + @PROTOCOLO + '%'
AND EC.TX_CPF_CNPJ like '%' + @CPF_CNPJ + '%'
AND ISNULL(ESR.CDA_ESTADO_REGIAO, 0) = COALESCE(@CEA_ESTADO_REGIAO, ISNULL(ESR.CDA_ESTADO_REGIAO, 0))
AND ISNULL(TE.TX_SEXO_CONTATO, 0) = COALESCE(@TX_SEXO_CONTATO, ISNULL(TE.TX_SEXO_CONTATO, 0))
AND TE.DT_ULTIMA_ALTERACAO BETWEEN @DATAINICIO AND @DATAFIM
AND ISNULL(TE.NU_FUNCIONARIO, 0) = COALESCE(@NU_FUNCIONARIOS, ISNULL(TE.NU_FUNCIONARIO, 0))
AND ISNULL(TE.CEA_TIPO_EMPRESA, 0) =  COALESCE(@TIPO_EMPRESA, ISNULL(TE.CEA_TIPO_EMPRESA, 0))
-----------------------------------------------------------------------------

RETURN  
END  
    
--    
