USE [Sistema Gestao]
GO
/****** Object:  StoredProcedure [dbo].[STP_SelecionaQuestionariosPorTurmaEmpresa]    Script Date: 01/12/2011 14:42:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [dbo].[STP_SelecionaQuestionariosPorTurmaEmpresa]
(
 @nIdTurma INT,
 @nIdEmpCadastro INT
)
As    
BEGIN     
SET NOCOUNT ON  

	SELECT q.CDA_QUESTIONARIO,
		   q.TX_QUESTIONARIO,
		   q.TX_DESCRICAO,
		   q.FL_ATIVO,
		   q.FL_PUBLICADO,
		   ISNULL(qe.CDA_QUESTIONARIO_EMPRESA,0) AS FL_PARTICIPA,
		   q.NU_CICLO,
		   q.DT_QUESTIONARIO,
		   rtq.FL_OBRIGATORIO,
		   (ISNULL(RESP1.RESP_EMPRESA,0)*100/RESP2.RESP_TOTAL) AS PORCENTAGEM,
		   q.FL_PREENCHIMENTO_RAPIDO
	  FROM TBL_REL_TURMA_QUESTIONARIO rtq
INNER JOIN TBL_QUESTIONARIO q ON q.CDA_QUESTIONARIO = rtq.CEA_QUESTIONARIO
 LEFT JOIN (SELECT * FROM TBL_QUESTIONARIO_EMPRESA WHERE CEA_EMP_CADASTRO = @nIdEmpCadastro AND TX_PROTOCOLO IS NULL AND FL_ATIVO = 'False') qe ON qe.CEA_QUESTIONARIO = q.CDA_QUESTIONARIO
 LEFT JOIN (SELECT COUNT(*) AS RESP_EMPRESA, CEA_QUESTIONARIO_EMPRESA
				FROM TBL_QUESTIONARIO_EMPRESA_RESPOSTA 
				GROUP BY CEA_QUESTIONARIO_EMPRESA) RESP1 ON RESP1.CEA_QUESTIONARIO_EMPRESA = qe.CDA_QUESTIONARIO_EMPRESA
 LEFT JOIN (SELECT COUNT(*) AS RESP_TOTAL, TBL_CRITERIO.CEA_QUESTIONARIO
				FROM TBL_PERGUNTA, TBL_CRITERIO
				WHERE TBL_PERGUNTA.CEA_CRITERIO = TBL_CRITERIO.CDA_CRITERIO
				GROUP BY CEA_QUESTIONARIO) RESP2 ON RESP2.CEA_QUESTIONARIO = qe.CEA_QUESTIONARIO
	 WHERE rtq.CEA_TURMA = @nIdTurma AND q.FL_PUBLICADO = 'True'
  ORDER BY rtq.FL_OBRIGATORIO DESC, q.TX_QUESTIONARIO
  
RETURN  
END  
    
--    
