
CREATE TABLE TBL_ADM_FUNCIONALIDADE
(
	CDA_FUNCIONALIDADE   int IDENTITY (1,1) ,
	CEA_TIPOFUNCIONALIDADE int  NOT NULL ,
	CEA_FUNCIONALIDADE_ORIGEM int  NULL ,
	TX_FUNCIONALIDADE    varchar(200)  NOT NULL ,
	TX_URL               varchar(500)  NULL ,
	TX_TABLE             varchar(200)  NULL ,
	FL_MOSTRA_MENU       bit  NULL 
)
go


ALTER TABLE TBL_ADM_FUNCIONALIDADE
	ADD CONSTRAINT PK_FUNC PRIMARY KEY  CLUSTERED (CDA_FUNCIONALIDADE ASC)
go


CREATE TABLE TBL_ADM_GRUPO
(
	CDA_GRUPO            int IDENTITY (1,1) ,
	TX_GRUPO             varchar(200)  NOT NULL 
)
go


ALTER TABLE TBL_ADM_GRUPO
	ADD CONSTRAINT PK_TBL_ADM_GRUPO PRIMARY KEY  CLUSTERED (CDA_GRUPO ASC)
go


CREATE TABLE TBL_ADM_RELFUNCGRUPO
(
	CEA_FUNCIONALIDADE   int  NOT NULL ,
	CEA_GRUPO            int  NOT NULL ,
	FL_INSERIR           bit  NULL ,
	FL_ATUALIZAR         bit  NULL ,
	FL_EXCLUIR           bit  NULL 
)
go


ALTER TABLE TBL_ADM_RELFUNCGRUPO
	ADD CONSTRAINT PK_TBL_ADM_RELFUNCGRUPO PRIMARY KEY  CLUSTERED (CEA_FUNCIONALIDADE ASC,CEA_GRUPO ASC)
go


CREATE TABLE TBL_ADM_RELGRUPOUSUARIO
(
	CEA_USUARIO          int  NOT NULL ,
	CEA_GRUPO            int  NOT NULL ,
	CDA_RELGRUPOUSUARIO  int IDENTITY (1,1) ,
	CEA_ESCRITORIO_REGIONAL int  NULL ,
	CEA_ESTADO           int  NULL ,
	CEA_TURMA            int  NULL ,
	CEA_PROGRAMA         int  NULL 
)
go


ALTER TABLE TBL_ADM_RELGRUPOUSUARIO
	ADD CONSTRAINT PK_TBL_ADM_RELGRUPOUSUARIO PRIMARY KEY  CLUSTERED (CDA_RELGRUPOUSUARIO ASC)
go


CREATE TABLE TBL_ADM_TIPOFUNCIONALIDADE
(
	CDA_TIPOFUNCIONALIDADE int IDENTITY (1,1) ,
	TX_TIPOFUNCIONALIDADE char(10)  NULL 
)
go


ALTER TABLE TBL_ADM_TIPOFUNCIONALIDADE
	ADD CONSTRAINT PK_systype PRIMARY KEY  CLUSTERED (CDA_TIPOFUNCIONALIDADE ASC)
go


CREATE TABLE TBL_ADM_USUARIO
(
	CDA_USUARIO          int IDENTITY (1,1) ,
	TX_USUARIO           varchar(200)  NOT NULL ,
	TX_LOGIN             varchar(200)  NOT NULL ,
	TX_SENHA             varchar(200)  NOT NULL ,
	CEA_ESTADO           int  NULL ,
	FL_ATIVO             bit  NOT NULL 
	CONSTRAINT DF_TBL_ADM_USUARIO_FL_ATIVO
		 DEFAULT  (0),
	TX_CPF               varchar(11)  NULL ,
	TX_TELEFONE          varchar(40)  NULL ,
	TX_EMAIL             varchar(200)  NULL 
)
go


ALTER TABLE TBL_ADM_USUARIO
	ADD CONSTRAINT PK_TBL_ADM_USUARIO PRIMARY KEY  CLUSTERED (CDA_USUARIO ASC)
go


CREATE TABLE TBL_ATIVIDADE_ECONOMICA
(
	CDA_ATIVIDADE_ECONOMICA int IDENTITY (1,1) ,
	TX_ATIVIDADE_ECONOMICA varchar(200)  NOT NULL ,
	FL_ATIVO             bit  NOT NULL 
	CONSTRAINT DF_TBL_ATIVIDADE_ECONOMICA_FL_ATIVO
		 DEFAULT  (0),
	TX_SECAO             varchar(5)  NULL ,
	TX_DIVISAO           varchar(5)  NULL ,
	TX_GRUPO             varchar(5)  NULL ,
	TX_CLASSE            varchar(50)  NULL 
)
go


ALTER TABLE TBL_ATIVIDADE_ECONOMICA
	ADD CONSTRAINT PK_TBL_RAMO_ATIVIDADE PRIMARY KEY  CLUSTERED (CDA_ATIVIDADE_ECONOMICA ASC)
go


CREATE TABLE TBL_CATEGORIA
(
	CDA_CATEGORIA        int IDENTITY (1,1) ,
	TX_CATEGORIA         varchar(200)  NOT NULL ,
	FL_ATIVO             bit  NOT NULL 
	CONSTRAINT DF_TBCNAESetor_FL_aTIVO
		 DEFAULT  (0)
)
go


ALTER TABLE TBL_CATEGORIA
	ADD CONSTRAINT PK_TBCNAESetor PRIMARY KEY  CLUSTERED (CDA_CATEGORIA ASC)
go


CREATE TABLE TBL_CHAMADO
(
	CDA_CHAMADO          int IDENTITY (1,1) ,
	TX_CHAMADO           varchar(200)  NULL ,
	NU_STATUS            int  NULL ,
	DT_CADASTRO          datetime  NULL ,
	DT_ALTERACAO         datetime  NULL ,
	CEA_USUARIO          int  NULL ,
	CEA_EMP_CADASTRO     int  NULL ,
	CEA_PROGRAMA         int  NULL 
)
go


ALTER TABLE TBL_CHAMADO
	ADD CONSTRAINT XPKTBL_CHAMADO PRIMARY KEY  CLUSTERED (CDA_CHAMADO ASC)
go


CREATE TABLE TBL_CIDADE
(
	CDA_CIDADE           int IDENTITY (1,1) ,
	CEA_ESCRITORIO_REGIONAL int  NOT NULL ,
	CEA_ESTADO_REGIAO    int  NULL ,
	TX_CIDADE            varchar(200)  NOT NULL ,
	FL_ATIVO             bit  NOT NULL 
	CONSTRAINT DF_TBL_CIDADE_FL_ATIVO
		 DEFAULT  (1)
)
go


ALTER TABLE TBL_CIDADE
	ADD CONSTRAINT PK_TBL_CIDADE PRIMARY KEY  CLUSTERED (CDA_CIDADE ASC)
go


CREATE TABLE TBL_CONTATO_FAIXA_ETARIA
(
	CDA_FAIXA_ETARIA     int IDENTITY (1,1) ,
	TX_FAIXA_ETARIA      text  NULL 
)
TEXTIMAGE_ON [PRIMARY]
go


ALTER TABLE TBL_CONTATO_FAIXA_ETARIA
	ADD CONSTRAINT PK_CONTATO_FAIXA_ETARIA PRIMARY KEY  CLUSTERED (CDA_FAIXA_ETARIA ASC)
go


CREATE TABLE TBL_CONTATO_NIVEL_ESCOLARIDADE
(
	CDA_NIVEL_ESCOLARIDADE int IDENTITY (1,1) ,
	TX_NIVEL_ESCOLARIDADE text  NULL ,
	NU_ORDEM             int  NULL 
)
TEXTIMAGE_ON [PRIMARY]
go


ALTER TABLE TBL_CONTATO_NIVEL_ESCOLARIDADE
	ADD CONSTRAINT PK_CONTATO_NIVEL_ESCOLARIDADE PRIMARY KEY  CLUSTERED (CDA_NIVEL_ESCOLARIDADE ASC)
go


CREATE TABLE TBL_CONTEUDO
(
	CDA_CONTEUDO         int IDENTITY (1,1) ,
	TX_TITULO            varchar(200)  NOT NULL ,
	TX_CONTEUDO          varchar(200)  NOT NULL ,
	DT_CADASTRO          datetime  NOT NULL ,
	DT_ATUALIZACAO       datetime  NULL ,
	FL_ATIVO             bit  NOT NULL 
	CONSTRAINT DF_TBL_CONTEUDO_FL_ATIVO
		 DEFAULT  (0),
	CEA_ESTADO           int  NULL ,
	CEA_ESCRITORIO_REGIONAL int  NULL ,
	CEA_PROGRAMA         int  NULL 
)
go


ALTER TABLE TBL_CONTEUDO
	ADD CONSTRAINT PK_TBL_CONTEUDO PRIMARY KEY  CLUSTERED (CDA_CONTEUDO ASC)
go


CREATE TABLE TBL_CRITERIO
(
	CDA_CRITERIO         int IDENTITY (1,1) ,
	TX_CRITERIO          varchar(200)  NOT NULL ,
	NU_ORDEM             int  NULL ,
	CEA_QUESTIONARIO     int  NULL 
)
go


ALTER TABLE TBL_CRITERIO
	ADD CONSTRAINT PK_TBL_CRITERIO PRIMARY KEY  CLUSTERED (CDA_CRITERIO ASC)
go


CREATE TABLE TBL_DOWNLOAD
(
	CDA_DOWNLOAD         int IDENTITY (1,1) ,
	CEA_ESTADO           int  NOT NULL ,
	TX_PATH              varchar(200)  NOT NULL ,
	CEA_ESCRITORIO_REGIONAL int  NULL ,
	CEA_PROGRAMA         int  NULL 
)
go


ALTER TABLE TBL_DOWNLOAD
	ADD CONSTRAINT PK_TBL_DOWNLOAD PRIMARY KEY  CLUSTERED (CDA_DOWNLOAD ASC)
go


CREATE TABLE TBL_EMP_CADASTRO
(
	CDA_EMP_CADASTRO     int IDENTITY (1,1) ,
	TX_RAZAO_SOCIAL      varchar(200)  NOT NULL ,
	TX_NOME_FANTASIA     varchar(200)  NOT NULL ,
	TX_CPF_CNPJ          varchar(20)  NOT NULL ,
	FL_PESSOA_JURIDICA   bit  NOT NULL 
	CONSTRAINT DF_TBL_CADASTRO_FL_PESSOA_JURIDICA
		 DEFAULT  (0),
	TX_SENHA             varchar(100)  NOT NULL ,
	FL_ATIVO             bit  NOT NULL 
	CONSTRAINT DF_TBL_CADASTRO_FL_ATIVO
		 DEFAULT  (1),
	DT_ABERTURA_EMPRESA  datetime  NULL ,
	FL_PARTICIPOU_MPE_2006 int  NULL ,
	FL_PARTICIPOU_MPE_2007 int  NULL ,
	FL_PARTICIPOU_MPE_2008 int  NULL ,
	FL_PARTICIPOU_MPE_2009 int  NULL ,
	FL_PARTICIPOU_MPE_2010 int  NULL ,
	FL_PARTICIPOU_MPE_2011 int  NULL 
)
go


ALTER TABLE TBL_EMP_CADASTRO
	ADD CONSTRAINT PK_TBL_CADASTRO PRIMARY KEY  CLUSTERED (CDA_EMP_CADASTRO ASC)
go


CREATE UNIQUE NONCLUSTERED INDEX IX_TBL_CADASTRO ON TBL_EMP_CADASTRO
(
	CDA_EMP_CADASTRO      ASC,
	TX_CPF_CNPJ           ASC
)
go


CREATE UNIQUE NONCLUSTERED INDEX IX_TBL_EMP_CADASTRO ON TBL_EMP_CADASTRO
(
	TX_CPF_CNPJ           ASC
)
go


CREATE TABLE TBL_ESCRITORIO_REGIONAL
(
	CDA_ESCRITORIO_REGIONAL int IDENTITY (1,1) ,
	CEA_ESTADO           int  NOT NULL ,
	TX_ESCRITORIO_REGIONAL varchar(200)  NOT NULL ,
	FL_ATIVO             bit  NOT NULL 
	CONSTRAINT DF_TBL_ESCRITORIO_REGIONAL_FL_ATIVO
		 DEFAULT  (1),
	CEA_TURMA            int  NULL 
)
go


ALTER TABLE TBL_ESCRITORIO_REGIONAL
	ADD CONSTRAINT PK_TBL_ESCRITORIO_REGIONAL PRIMARY KEY  CLUSTERED (CDA_ESCRITORIO_REGIONAL ASC)
go


CREATE TABLE TBL_ESTADO
(
	CDA_ESTADO           int IDENTITY (1,1) ,
	TX_ESTADO            varchar(200)  NOT NULL ,
	TX_STYLE             varchar(200)  NULL ,
	TX_EMAIL             varchar(200)  NULL ,
	FL_ATIVO             bit  NOT NULL 
	CONSTRAINT DF_TBL_ESTADO_FL_ATIVO
		 DEFAULT  (1)
)
go


ALTER TABLE TBL_ESTADO
	ADD CONSTRAINT PK_TBL_ESTADO PRIMARY KEY  CLUSTERED (CDA_ESTADO ASC)
go


CREATE TABLE TBL_ESTADO_REGIAO
(
	CDA_ESTADO_REGIAO    int IDENTITY (1,1) ,
	CEA_ESTADO           int  NOT NULL ,
	TX_ESTADO_REGIAO     varchar(200)  NOT NULL ,
	FL_ATIVO             bit  NOT NULL 
	CONSTRAINT DF_TBL_ESTADO_REGIAO_FL_ATIVO
		 DEFAULT  (1)
)
go


ALTER TABLE TBL_ESTADO_REGIAO
	ADD CONSTRAINT PK_TBL_ESTADO_REGIAO PRIMARY KEY  CLUSTERED (CDA_ESTADO_REGIAO ASC)
go


CREATE TABLE TBL_ETAPA
(
	CDA_ETAPA            int IDENTITY (1,1) ,
	TX_ETAPA             varchar(200)  NULL ,
	CEA_TURMA            int  NULL ,
	FL_ATIVO             int  NULL ,
	CEA_TIPO_ETAPA       int  NULL 
)
go


ALTER TABLE TBL_ETAPA
	ADD CONSTRAINT XPKTBL_ETAPA PRIMARY KEY  CLUSTERED (CDA_ETAPA ASC)
go


CREATE TABLE TBL_FATURAMENTO
(
	CDA_FATURAMENTO      int IDENTITY (1,1) ,
	TX_FATURAMENTO       varchar(200)  NOT NULL ,
	TX_MENSURACAO_FATURAMENTO varchar(200)  NOT NULL ,
	CEA_FATURAMENTO_TIPO int  NOT NULL ,
	CONSTRAINT  CK_TBL_FATURAMENTO
		CHECK  ( ( [TX_MENSURACAO_FATURAMENTO] =    'PADRÃO' OR [TX_MENSURACAO_FATURAMENTO] =    'CUSTOMIZADA' ) ) 
)
go


ALTER TABLE TBL_FATURAMENTO
	ADD CONSTRAINT PK_TBL_FATURAMENTO PRIMARY KEY  CLUSTERED (CDA_FATURAMENTO ASC)
go


CREATE TABLE TBL_FATURAMENTO_TIPO
(
	CDA_FATURAMENTO_TIPO int IDENTITY (1,1) ,
	TX_FATURAMENTO_TIPO  varchar(20)  NULL ,
	FL_ATIVO             bit  NULL 
)
go


ALTER TABLE TBL_FATURAMENTO_TIPO
	ADD CONSTRAINT XPKTBL_FATURAMENTO_TIPO PRIMARY KEY  CLUSTERED (CDA_FATURAMENTO_TIPO ASC)
go


CREATE TABLE TBL_GRUPO
(
	CDA_GRUPO            int IDENTITY (1,1) ,
	TX_GRUPO             varchar(200)  NULL ,
	FL_ATIVO             bit  NULL ,
	CEA_TURMA            int  NULL ,
	CEA_ESTADO           int  NULL 
)
go


ALTER TABLE TBL_GRUPO
	ADD CONSTRAINT PK__TBL_GRUPO__2453463D PRIMARY KEY  CLUSTERED (CDA_GRUPO ASC)
go


CREATE TABLE TBL_GRUPOEMPRESA
(
	CDA_GRUPO_EMPRESA    int IDENTITY (1,1) ,
	DT_CADASTRO          datetime  NULL ,
	CEA_GRUPO            int  NULL ,
	CEA_EMP_CADASTRO     int  NULL 
)
go


ALTER TABLE TBL_GRUPOEMPRESA
	ADD CONSTRAINT PK__TBL_GRUPOEMPRESA__263B8EAF PRIMARY KEY  CLUSTERED (CDA_GRUPO_EMPRESA ASC)
go


CREATE TABLE TBL_LOG_ACAO
(
	CDA_LOG_ACAO         int IDENTITY (1,1) ,
	CEA_USUARIO          int  NULL ,
	CEA_EMP_CADASTRO     int  NULL ,
	TX_ACAO              varchar(20)  NULL ,
	CEA_TIPO_ACAO        int  NULL 
)
go


ALTER TABLE TBL_LOG_ACAO
	ADD CONSTRAINT XPKTBL_LOG_ACTION PRIMARY KEY  CLUSTERED (CDA_LOG_ACAO ASC)
go


CREATE TABLE TBL_PAIS
(
	CDA_PAIS             int IDENTITY (1,1) ,
	TX_PAIS              varchar(200)  NOT NULL ,
	FL_ATIVO             bit  NOT NULL 
	CONSTRAINT DF_TBL_PAIS_FL_ATIVO
		 DEFAULT  (0)
)
go


ALTER TABLE TBL_PAIS
	ADD CONSTRAINT PK_TBL_PAIS PRIMARY KEY  CLUSTERED (CDA_PAIS ASC)
go


CREATE TABLE TBL_PERGUNTA
(
	CDA_PERGUNTA         int IDENTITY (1,1) ,
	TX_PERGUNTA          varchar(1000)  NOT NULL ,
	NU_ORDEM             int  NOT NULL ,
	FL_ATIVO             bit  NOT NULL 
	CONSTRAINT DF_TBL_PERGUNTA_FL_ATIVO
		 DEFAULT  (0),
	TX_GLOSSARIO         varchar(2000)  NULL ,
	TX_SAIBA_MAIS        varchar(2000)  NULL ,
	CEA_PERGUNTA_TIPO    int  NULL ,
	CEA_CRITERIO         int  NULL 
)
go


ALTER TABLE TBL_PERGUNTA
	ADD CONSTRAINT PK_TBL_PERGUNTA PRIMARY KEY  CLUSTERED (CDA_PERGUNTA ASC)
go


CREATE TABLE TBL_PERGUNTA_RESPOSTA
(
	CDA_RESPOSTA         int IDENTITY (1,1) ,
	LBL_RESPOSTA         varchar(500)  NOT NULL ,
	NU_ORDEM             int  NOT NULL 
	CONSTRAINT DF_TBL_PERGUNTA_RESPOSTA_NU_ORDEM
		 DEFAULT  (0),
	NU_PONTO             decimal(18,5)  NOT NULL 
	CONSTRAINT DF_TBL_PERGUNTA_RESPOSTA_NU_PONTO
		 DEFAULT  (0),
	TX_RESPOSTA_AUTOMATICA varchar(1000)  NULL ,
	CEA_PERGUNTA         int  NULL ,
	FL_POSSUI_JUSTIFICATIVA bit  NULL ,
	LBL_VALOR_01         varchar(20)  NULL ,
	LBL_VALOR_02         varchar(20)  NULL ,
	LBL_VALOR_03         varchar(20)  NULL ,
	LBL_VALOR_04         varchar(20)  NULL ,
	LBL_VALOR_05         varchar(20)  NULL ,
	LBL_VALOR_06         varchar(20)  NULL ,
	LBL_VALOR_07         varchar(20)  NULL ,
	LBL_VALOR_08         varchar(20)  NULL ,
	LBL_VALOR_09         varchar(20)  NULL ,
	LBL_VALOR_10         varchar(20)  NULL 
)
go


ALTER TABLE TBL_PERGUNTA_RESPOSTA
	ADD CONSTRAINT PK_TBL_PERGUNTA_RESPOSTA PRIMARY KEY  CLUSTERED (CDA_RESPOSTA ASC)
go


CREATE TABLE TBL_PERGUNTA_TIPO
(
	CDA_PERGUNTA_TIPO    int IDENTITY (1,1) ,
	TX_PERGUNTA_TIPO     varchar(200)  NULL 
)
go


ALTER TABLE TBL_PERGUNTA_TIPO
	ADD CONSTRAINT XPKTBL_PERGUNTA_TIPO PRIMARY KEY  CLUSTERED (CDA_PERGUNTA_TIPO ASC)
go


CREATE TABLE TBL_PROGRAMA
(
	CDA_PROGRAMA         int IDENTITY (1,1) ,
	TX_PROGRAMA          varchar(200)  NOT NULL ,
	FL_PUBLICO           bit  NOT NULL 
	CONSTRAINT Default_Value_1013_1310341959
		 DEFAULT  ((1)),
	FL_PUBLICADO         bit  NOT NULL 
	CONSTRAINT Default_Value_1016_1362590830
		 DEFAULT  ((1)),
	FL_ATIVO             bit  NOT NULL 
	CONSTRAINT Default_Value_1019_383727671
		 DEFAULT  ((1)),
	DT_CADASTRO          datetime  NOT NULL 
)
go


ALTER TABLE TBL_PROGRAMA
	ADD CONSTRAINT PK_TBL_PROGRAMA PRIMARY KEY  CLUSTERED (CDA_PROGRAMA ASC)
go


CREATE TABLE TBL_QUESTIONARIO
(
	CDA_QUESTIONARIO     int IDENTITY (1,1) ,
	TX_QUESTIONARIO      varchar(200)  NOT NULL ,
	DT_QUESTIONARIO      datetime  NOT NULL ,
	FL_ATIVO             bit  NOT NULL 
	CONSTRAINT DF_TBL_QUESTIONARIO_FL_ATIVO
		 DEFAULT  (0),
	FL_PUBLICADO         bit  NOT NULL 
	CONSTRAINT DF_TBL_QUESTIONARIO_FL_PUBLICADO
		 DEFAULT  (0),
	NU_CICLO             int  NULL 
)
go


ALTER TABLE TBL_QUESTIONARIO
	ADD CONSTRAINT PK_TBL_QUESTIONARIO PRIMARY KEY  CLUSTERED (CDA_QUESTIONARIO ASC)
go


CREATE TABLE TBL_QUESTIONARIO_EMPRESA
(
	CDA_QUESTIONARIO_EMPRESA int IDENTITY (1,1) ,
	CEA_PROGRAMA         int  NOT NULL ,
	CEA_EMP_CADASTRO     int  NOT NULL ,
	DT_CADASTRO          datetime  NOT NULL ,
	FL_ATIVO             bit  NOT NULL 
	CONSTRAINT DF_TBL_QUESTIONARIO_EMPRESA_FL_ATIVO
		 DEFAULT  (1),
	TX_PROTOCOLO         varchar(200)  NULL ,
	CEA_USUARIO          int  NULL ,
	DT_ALTERACAO         datetime  NULL ,
	TX_MOTIVO_VENCEU     varchar(200)  NULL ,
	TX_MOTIVO_EXCLUIU    varchar(200)  NULL ,
	FL_LEITURA           bit  NOT NULL 
	CONSTRAINT Default_Value_936_374013482
		 DEFAULT  ((0)),
	NU_TOTAL_PONTUACAO   int  NULL ,
	FL_SINCRONIZADO_SIAC int  NULL ,
	CEA_ETAPA            int  NULL ,
	FL_PASSA_PROXIMA_ETAPA int  NULL 
)
go


ALTER TABLE TBL_QUESTIONARIO_EMPRESA
	ADD CONSTRAINT PK_TBL_QUESTIONARIO_EMPRESA PRIMARY KEY  CLUSTERED (CDA_QUESTIONARIO_EMPRESA ASC)
go


CREATE TABLE TBL_QUESTIONARIO_EMPRESA_AVALIADOR
(
	CDA_QUESTIONARIO_EMPRESA_AVALIADOR int IDENTITY (1,1) ,
	CEA_QUESTIONARIO_EMPRESA int  NOT NULL ,
	CEA_USUARIO          int  NOT NULL ,
	FL_AVALIADO          bit  NULL ,
	TX_MOTIVO_DEVOLUCAO  varchar(200)  NULL ,
	TX_MELHOR_PRATICA    varchar(200)  NULL ,
	TX_BANCA             text  NULL ,
	FL_PRIMARIO          int  NULL 
)
TEXTIMAGE_ON [PRIMARY]
go


ALTER TABLE TBL_QUESTIONARIO_EMPRESA_AVALIADOR
	ADD CONSTRAINT PK_TBL_QUESTIONARIO_EMPRESA_AVALIADOR PRIMARY KEY  CLUSTERED (CDA_QUESTIONARIO_EMPRESA_AVALIADOR ASC)
go


CREATE TABLE TBL_QUESTIONARIO_EMPRESA_RESPOSTA
(
	CEA_QUESTIONARIO_EMPRESA int  NOT NULL ,
	CEA_PERGUNTA         int  NOT NULL ,
	CEA_RESPOSTA         int  NOT NULL ,
	TX_RESPOSTA          ntext  NULL ,
	TX_JUSTIFICATIVA     varchar(20)  NULL ,
	TX_VALOR_01          decimal(10,2)  NULL ,
	TX_VALOR_02          decimal(10,2)  NULL ,
	TX_VALOR_03          decimal(10,2)  NULL ,
	TX_OPORTUNIDADE_MELHORIA varchar(20)  NULL ,
	TX_PONTO_FORTE       varchar(20)  NULL ,
	CEA_USUARIO_DIGITADOR int  NULL ,
	FL_RESPOSTA_BOOL     int  NULL ,
	TX_VALOR_04          decimal(10,2)  NULL ,
	TX_VALOR_05          decimal(10,2)  NULL ,
	TX_VALOR_06          decimal(10,2)  NULL ,
	TX_VALOR_07          decimal(10,2)  NULL ,
	TX_VALOR_08          decimal(10,2)  NULL ,
	TX_VALOR_09          decimal(10,2)  NULL ,
	TX_VALOR_10          decimal(10,2)  NULL ,
	CEA_USUARIO_AVALIADOR int  NULL 
)
TEXTIMAGE_ON [PRIMARY]
go


ALTER TABLE TBL_QUESTIONARIO_EMPRESA_RESPOSTA
	ADD CONSTRAINT PK_TBL_QUESTIONARIO_EMPRESA_RESPOSTA PRIMARY KEY  CLUSTERED (CEA_QUESTIONARIO_EMPRESA ASC,CEA_PERGUNTA ASC,CEA_RESPOSTA ASC)
go


CREATE TABLE TBL_QUESTIONARIO_PONTUACAO
(
	CEA_QUESTIONARIO_EMPRESA int  NOT NULL ,
	CEA_CRITERIO         int  NULL ,
	NU_PONTO             decimal(18,5)  NOT NULL ,
	CEA_QUESTIONARIO     int  NULL 
)
go


CREATE TABLE TBL_REL_CATEGORIA_ATIVIDADE_ECONOMICA
(
	CEA_ATIVIDADE_ECONOMICA int  NOT NULL ,
	CEA_CATEGORIA        int  NOT NULL 
)
go


ALTER TABLE TBL_REL_CATEGORIA_ATIVIDADE_ECONOMICA
	ADD CONSTRAINT PK_TBL_REL_CATEGORIA_RAMO_ATIVIDADE PRIMARY KEY  CLUSTERED (CEA_ATIVIDADE_ECONOMICA ASC,CEA_CATEGORIA ASC)
go


CREATE TABLE TBL_REL_CICLO_QUESTIONARIO
(
	CEA_QUESTIONARIO     int  NOT NULL ,
	CEA_TURMA            int  NOT NULL 
)
go


ALTER TABLE TBL_REL_CICLO_QUESTIONARIO
	ADD CONSTRAINT XPKTBL_REL_CICLO_QUESTIONARIO PRIMARY KEY  CLUSTERED (CEA_QUESTIONARIO ASC,CEA_TURMA ASC)
go


CREATE TABLE TBL_TIPO_ACAO
(
	CDA_TIPO_ACAO        int IDENTITY (1,1) ,
	TX_TIPO_ACAO         varchar(20)  NULL 
)
go


ALTER TABLE TBL_TIPO_ACAO
	ADD CONSTRAINT XPKTBL_TIPO_ACAO PRIMARY KEY  CLUSTERED (CDA_TIPO_ACAO ASC)
go


CREATE TABLE TBL_TIPO_EMP
(
	CDA_TIPO_EMPRESA     int IDENTITY (1,1) ,
	TX_TIPO_EMPRESA      varchar(200)  NULL 
)
go


ALTER TABLE TBL_TIPO_EMP
	ADD CONSTRAINT XPKTBL_TIPO_EMP PRIMARY KEY  CLUSTERED (CDA_TIPO_EMPRESA ASC)
go


CREATE TABLE TBL_TIPO_ETAPA
(
	CDA_TIPO_ETAPA       int IDENTITY (1,1) ,
	TX_TIPO_ETAPA        varchar(200)  NULL 
)
go


ALTER TABLE TBL_TIPO_ETAPA
	ADD CONSTRAINT XPKTBL_TIPO_ETAPA PRIMARY KEY  CLUSTERED (CDA_TIPO_ETAPA ASC)
go


CREATE TABLE TBL_TURMA
(
	CEA_PROGRAMA         int  NULL ,
	CDA_TURMA            int IDENTITY (1,1) ,
	TX_CICLO             varchar(200)  NULL ,
	FL_ATIVO             int  NULL ,
	DT_CADASTRO          datetime  NULL 
)
go


ALTER TABLE TBL_TURMA
	ADD CONSTRAINT XPKTBL_CICLO PRIMARY KEY  CLUSTERED (CDA_TURMA ASC)
go


CREATE TABLE TBL_TURMA_EMP
(
	CEA_EMP_CADASTRO     int  NOT NULL ,
	CEA_CATEGORIA        int  NULL ,
	CEA_ATIVIDADE_ECONOMICA int  NULL ,
	CEA_FATURAMENTO      int  NULL ,
	NU_FUNCIONARIO       int  NULL ,
	TX_CEP               varchar(18)  NULL ,
	TX_BAIRRO            varchar(200)  NULL ,
	TX_ENDERECO          varchar(300)  NULL ,
	TX_COMPLEMENTO       varchar(40)  NULL ,
	FL_ATIVO             bit  NOT NULL 
	CONSTRAINT Default_Value_461_204158776
		 DEFAULT  ((1)),
	CEA_USUARIO          int  NULL ,
	CEA_CIDADE           int  NULL ,
	DT_ULTIMA_ALTERACAO  datetime  NULL ,
	CEA_ESTADO           int  NULL ,
	CEA_PAIS             int  NULL ,
	DT_CADASTRO          datetime  NOT NULL ,
	TX_ATIVIDADE_ECONOMICA varchar(200)  NULL ,
	FL_PARTICIPA_PROGRAMA bit  NOT NULL 
	CONSTRAINT Default_Value_474_606934808
		 DEFAULT  ('FALSE'),
	TX_NOME_CONTATO      varchar(200)  NULL ,
	TX_CARGO_CONTATO     varchar(200)  NULL ,
	TX_TELEFONE_CONTATO  varchar(20)  NULL ,
	TX_CELULAR_CONTATO   varchar(20)  NULL ,
	TX_EMAIL_CONTATO     varchar(200)  NULL ,
	TX_MENSAGEM_CONTATO  varchar(200)  NULL ,
	TX_CPF_CONTATO       varchar(11)  NULL ,
	DT_DATA_NASCIMENTO_CONTATO Datetime  NULL ,
	TX_ENDERECO_CONTATO  varchar(200)  NULL ,
	TX_SEXO_CONTATO      char(1)  NULL ,
	CEA_NIVEL_ESCOLARIDADE int  NULL ,
	CEA_FAIXA_ETARIA     int  NULL ,
	CEA_TURMA            int  NOT NULL ,
	CEA_TIPO_EMPRESA     int  NULL 
)
go


ALTER TABLE TBL_TURMA_EMP
	ADD CONSTRAINT PK_TBL_REL_EMP_PROGRAMA PRIMARY KEY  CLUSTERED (CEA_EMP_CADASTRO ASC,DT_CADASTRO ASC,CEA_TURMA ASC)
go



ALTER TABLE TBL_ADM_FUNCIONALIDADE
	ADD CONSTRAINT  FK_TBL_ADM_FUNCIONALIDADE_TBL_ADM_FUNCIONALIDADE FOREIGN KEY (CEA_FUNCIONALIDADE_ORIGEM) REFERENCES TBL_ADM_FUNCIONALIDADE(CDA_FUNCIONALIDADE)
go

ALTER TABLE TBL_ADM_FUNCIONALIDADE
	ADD CONSTRAINT  FK_TBL_ADM_FUNCIONALIDADE_TBL_ADM_TIPOFUNCIONALIDADE FOREIGN KEY (CEA_TIPOFUNCIONALIDADE) REFERENCES TBL_ADM_TIPOFUNCIONALIDADE(CDA_TIPOFUNCIONALIDADE)
go



ALTER TABLE TBL_ADM_RELFUNCGRUPO
	ADD CONSTRAINT  FK_TBL_ADM_RELFUNCGRUPO_TBL_ADM_FUNCIONALIDADE FOREIGN KEY (CEA_FUNCIONALIDADE) REFERENCES TBL_ADM_FUNCIONALIDADE(CDA_FUNCIONALIDADE)
		ON DELETE CASCADE
go

ALTER TABLE TBL_ADM_RELFUNCGRUPO
	ADD CONSTRAINT  FK_TBL_ADM_RELFUNCGRUPO_TBL_ADM_GRUPO FOREIGN KEY (CEA_GRUPO) REFERENCES TBL_ADM_GRUPO(CDA_GRUPO)
		ON DELETE CASCADE
go



ALTER TABLE TBL_ADM_RELGRUPOUSUARIO
	ADD CONSTRAINT  FK_TBL_ADM_RELGRUPOUSUARIO_TBL_ADM_GRUPO FOREIGN KEY (CEA_GRUPO) REFERENCES TBL_ADM_GRUPO(CDA_GRUPO)
go

ALTER TABLE TBL_ADM_RELGRUPOUSUARIO
	ADD CONSTRAINT  FK_TBL_ADM_RELGRUPOUSUARIO_TBL_ADM_USUARIO FOREIGN KEY (CEA_USUARIO) REFERENCES TBL_ADM_USUARIO(CDA_USUARIO)
		ON DELETE CASCADE
go

ALTER TABLE TBL_ADM_RELGRUPOUSUARIO
	ADD CONSTRAINT  R_140 FOREIGN KEY (CEA_ESCRITORIO_REGIONAL) REFERENCES TBL_ESCRITORIO_REGIONAL(CDA_ESCRITORIO_REGIONAL)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go

ALTER TABLE TBL_ADM_RELGRUPOUSUARIO
	ADD CONSTRAINT  R_141 FOREIGN KEY (CEA_ESTADO) REFERENCES TBL_ESTADO(CDA_ESTADO)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go

ALTER TABLE TBL_ADM_RELGRUPOUSUARIO
	ADD CONSTRAINT  R_142 FOREIGN KEY (CEA_TURMA) REFERENCES TBL_TURMA(CDA_TURMA)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go

ALTER TABLE TBL_ADM_RELGRUPOUSUARIO
	ADD CONSTRAINT  R_150 FOREIGN KEY (CEA_PROGRAMA) REFERENCES TBL_PROGRAMA(CDA_PROGRAMA)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go



ALTER TABLE TBL_CHAMADO
	ADD CONSTRAINT  R_134 FOREIGN KEY (CEA_USUARIO) REFERENCES TBL_ADM_USUARIO(CDA_USUARIO)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go

ALTER TABLE TBL_CHAMADO
	ADD CONSTRAINT  R_135 FOREIGN KEY (CEA_EMP_CADASTRO) REFERENCES TBL_EMP_CADASTRO(CDA_EMP_CADASTRO)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go

ALTER TABLE TBL_CHAMADO
	ADD CONSTRAINT  R_149 FOREIGN KEY (CEA_PROGRAMA) REFERENCES TBL_PROGRAMA(CDA_PROGRAMA)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go



ALTER TABLE TBL_CIDADE
	ADD CONSTRAINT  FK_TBL_CIDADE_TBL_ESCRITORIO_REGIONAL FOREIGN KEY (CEA_ESCRITORIO_REGIONAL) REFERENCES TBL_ESCRITORIO_REGIONAL(CDA_ESCRITORIO_REGIONAL)
go

ALTER TABLE TBL_CIDADE
	ADD CONSTRAINT  FK_TBL_CIDADE_TBL_ESTADO_REGIAO FOREIGN KEY (CEA_ESTADO_REGIAO) REFERENCES TBL_ESTADO_REGIAO(CDA_ESTADO_REGIAO)
go



ALTER TABLE TBL_CONTEUDO
	ADD CONSTRAINT  R_127 FOREIGN KEY (CEA_ESTADO) REFERENCES TBL_ESTADO(CDA_ESTADO)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go

ALTER TABLE TBL_CONTEUDO
	ADD CONSTRAINT  R_128 FOREIGN KEY (CEA_ESCRITORIO_REGIONAL) REFERENCES TBL_ESCRITORIO_REGIONAL(CDA_ESCRITORIO_REGIONAL)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go

ALTER TABLE TBL_CONTEUDO
	ADD CONSTRAINT  R_147 FOREIGN KEY (CEA_PROGRAMA) REFERENCES TBL_PROGRAMA(CDA_PROGRAMA)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go



ALTER TABLE TBL_CRITERIO
	ADD CONSTRAINT  R_138 FOREIGN KEY (CEA_QUESTIONARIO) REFERENCES TBL_QUESTIONARIO(CDA_QUESTIONARIO)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go



ALTER TABLE TBL_DOWNLOAD
	ADD CONSTRAINT  FK_TBL_DOWNLOAD_TBL_ESTADO FOREIGN KEY (CEA_ESTADO) REFERENCES TBL_ESTADO(CDA_ESTADO)
		ON DELETE CASCADE
go

ALTER TABLE TBL_DOWNLOAD
	ADD CONSTRAINT  R_131 FOREIGN KEY (CEA_ESCRITORIO_REGIONAL) REFERENCES TBL_ESCRITORIO_REGIONAL(CDA_ESCRITORIO_REGIONAL)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go

ALTER TABLE TBL_DOWNLOAD
	ADD CONSTRAINT  R_148 FOREIGN KEY (CEA_PROGRAMA) REFERENCES TBL_PROGRAMA(CDA_PROGRAMA)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go



ALTER TABLE TBL_ESCRITORIO_REGIONAL
	ADD CONSTRAINT  FK_TBL_ESCRITORIO_REGIONAL_TBL_ESTADO FOREIGN KEY (CEA_ESTADO) REFERENCES TBL_ESTADO(CDA_ESTADO)
go

ALTER TABLE TBL_ESCRITORIO_REGIONAL
	ADD CONSTRAINT  R_118 FOREIGN KEY (CEA_TURMA) REFERENCES TBL_TURMA(CDA_TURMA)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go



ALTER TABLE TBL_ESTADO_REGIAO
	ADD CONSTRAINT  FK_TBL_ESTADO_REGIAO_TBL_ESTADO FOREIGN KEY (CEA_ESTADO) REFERENCES TBL_ESTADO(CDA_ESTADO)
go



ALTER TABLE TBL_ETAPA
	ADD CONSTRAINT  R_119 FOREIGN KEY (CEA_TURMA) REFERENCES TBL_TURMA(CDA_TURMA)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go

ALTER TABLE TBL_ETAPA
	ADD CONSTRAINT  R_136 FOREIGN KEY (CEA_TIPO_ETAPA) REFERENCES TBL_TIPO_ETAPA(CDA_TIPO_ETAPA)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go



ALTER TABLE TBL_FATURAMENTO
	ADD CONSTRAINT  R_151 FOREIGN KEY (CEA_FATURAMENTO_TIPO) REFERENCES TBL_FATURAMENTO_TIPO(CDA_FATURAMENTO_TIPO)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go



ALTER TABLE TBL_GRUPO
	ADD CONSTRAINT  R_102 FOREIGN KEY (CEA_TURMA) REFERENCES TBL_TURMA(CDA_TURMA)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go

ALTER TABLE TBL_GRUPO
	ADD CONSTRAINT  R_152 FOREIGN KEY (CEA_ESTADO) REFERENCES TBL_ESTADO(CDA_ESTADO)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go



ALTER TABLE TBL_GRUPOEMPRESA
	ADD CONSTRAINT  R_124 FOREIGN KEY (CEA_GRUPO) REFERENCES TBL_GRUPO(CDA_GRUPO)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go

ALTER TABLE TBL_GRUPOEMPRESA
	ADD CONSTRAINT  R_125 FOREIGN KEY (CEA_EMP_CADASTRO) REFERENCES TBL_EMP_CADASTRO(CDA_EMP_CADASTRO)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go



ALTER TABLE TBL_LOG_ACAO
	ADD CONSTRAINT  R_111 FOREIGN KEY (CEA_USUARIO) REFERENCES TBL_ADM_USUARIO(CDA_USUARIO)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go

ALTER TABLE TBL_LOG_ACAO
	ADD CONSTRAINT  R_112 FOREIGN KEY (CEA_EMP_CADASTRO) REFERENCES TBL_EMP_CADASTRO(CDA_EMP_CADASTRO)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go

ALTER TABLE TBL_LOG_ACAO
	ADD CONSTRAINT  R_123 FOREIGN KEY (CEA_TIPO_ACAO) REFERENCES TBL_TIPO_ACAO(CDA_TIPO_ACAO)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go



ALTER TABLE TBL_PERGUNTA
	ADD CONSTRAINT  R_104 FOREIGN KEY (CEA_PERGUNTA_TIPO) REFERENCES TBL_PERGUNTA_TIPO(CDA_PERGUNTA_TIPO)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go

ALTER TABLE TBL_PERGUNTA
	ADD CONSTRAINT  R_137 FOREIGN KEY (CEA_CRITERIO) REFERENCES TBL_CRITERIO(CDA_CRITERIO)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go



ALTER TABLE TBL_PERGUNTA_RESPOSTA
	ADD CONSTRAINT  R_99 FOREIGN KEY (CEA_PERGUNTA) REFERENCES TBL_PERGUNTA(CDA_PERGUNTA)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go



ALTER TABLE TBL_QUESTIONARIO_EMPRESA
	ADD CONSTRAINT  FK_TBL_QUESTIONARIO_EMPRESA_TBL_EMP_CADASTRO FOREIGN KEY (CEA_EMP_CADASTRO) REFERENCES TBL_EMP_CADASTRO(CDA_EMP_CADASTRO)
		ON DELETE CASCADE
go

ALTER TABLE TBL_QUESTIONARIO_EMPRESA
	ADD CONSTRAINT  R_122 FOREIGN KEY (CEA_ETAPA) REFERENCES TBL_ETAPA(CDA_ETAPA)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go



ALTER TABLE TBL_QUESTIONARIO_EMPRESA_AVALIADOR
	ADD CONSTRAINT  FK_TBL_QUESTIONARIO_EMPRESA_AVALIADOR_TBL_ADM_USUARIO FOREIGN KEY (CEA_USUARIO) REFERENCES TBL_ADM_USUARIO(CDA_USUARIO)
go

ALTER TABLE TBL_QUESTIONARIO_EMPRESA_AVALIADOR
	ADD CONSTRAINT  FK_TBL_QUESTIONARIO_EMPRESA_AVALIADOR_TBL_QUESTIONARIO_EMPRESA FOREIGN KEY (CEA_QUESTIONARIO_EMPRESA) REFERENCES TBL_QUESTIONARIO_EMPRESA(CDA_QUESTIONARIO_EMPRESA)
		ON DELETE CASCADE
go



ALTER TABLE TBL_QUESTIONARIO_EMPRESA_RESPOSTA
	ADD CONSTRAINT  FK_TBL_QUESTIONARIO_EMPRESA_RESPOSTA_TBL_PERGUNTA FOREIGN KEY (CEA_PERGUNTA) REFERENCES TBL_PERGUNTA(CDA_PERGUNTA)
go

ALTER TABLE TBL_QUESTIONARIO_EMPRESA_RESPOSTA
	ADD CONSTRAINT  FK_TBL_QUESTIONARIO_EMPRESA_RESPOSTA_TBL_PERGUNTA_RESPOSTA FOREIGN KEY (CEA_RESPOSTA) REFERENCES TBL_PERGUNTA_RESPOSTA(CDA_RESPOSTA)
go

ALTER TABLE TBL_QUESTIONARIO_EMPRESA_RESPOSTA
	ADD CONSTRAINT  FK_TBL_QUESTIONARIO_EMPRESA_RESPOSTA_TBL_QUESTIONARIO_EMPRESA FOREIGN KEY (CEA_QUESTIONARIO_EMPRESA) REFERENCES TBL_QUESTIONARIO_EMPRESA(CDA_QUESTIONARIO_EMPRESA)
		ON DELETE CASCADE
go

ALTER TABLE TBL_QUESTIONARIO_EMPRESA_RESPOSTA
	ADD CONSTRAINT  R_105 FOREIGN KEY (CEA_USUARIO_DIGITADOR) REFERENCES TBL_ADM_USUARIO(CDA_USUARIO)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go

ALTER TABLE TBL_QUESTIONARIO_EMPRESA_RESPOSTA
	ADD CONSTRAINT  R_139 FOREIGN KEY (CEA_USUARIO_AVALIADOR) REFERENCES TBL_ADM_USUARIO(CDA_USUARIO)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go



ALTER TABLE TBL_QUESTIONARIO_PONTUACAO
	ADD CONSTRAINT  FK_TBL_QUESTIONARIO_PONTUACAO_TBL_CRITERIO FOREIGN KEY (CEA_CRITERIO) REFERENCES TBL_CRITERIO(CDA_CRITERIO)
go

ALTER TABLE TBL_QUESTIONARIO_PONTUACAO
	ADD CONSTRAINT  R_106 FOREIGN KEY (CEA_QUESTIONARIO) REFERENCES TBL_QUESTIONARIO(CDA_QUESTIONARIO)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go



ALTER TABLE TBL_REL_CATEGORIA_ATIVIDADE_ECONOMICA
	ADD CONSTRAINT  FK_TBL_REL_CATEGORIA_RAMO_ATIVIDADE_TBL_CATEGORIA FOREIGN KEY (CEA_CATEGORIA) REFERENCES TBL_CATEGORIA(CDA_CATEGORIA)
go

ALTER TABLE TBL_REL_CATEGORIA_ATIVIDADE_ECONOMICA
	ADD CONSTRAINT  FK_TBL_REL_CATEGORIA_RAMO_ATIVIDADE_TBL_RAMO_ATIVIDADE FOREIGN KEY (CEA_ATIVIDADE_ECONOMICA) REFERENCES TBL_ATIVIDADE_ECONOMICA(CDA_ATIVIDADE_ECONOMICA)
go



ALTER TABLE TBL_REL_CICLO_QUESTIONARIO
	ADD CONSTRAINT  R_116 FOREIGN KEY (CEA_QUESTIONARIO) REFERENCES TBL_QUESTIONARIO(CDA_QUESTIONARIO)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go

ALTER TABLE TBL_REL_CICLO_QUESTIONARIO
	ADD CONSTRAINT  R_117 FOREIGN KEY (CEA_TURMA) REFERENCES TBL_TURMA(CDA_TURMA)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go



ALTER TABLE TBL_TURMA
	ADD CONSTRAINT  R_101 FOREIGN KEY (CEA_PROGRAMA) REFERENCES TBL_PROGRAMA(CDA_PROGRAMA)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go



ALTER TABLE TBL_TURMA_EMP
	ADD CONSTRAINT  FK_TBL_PROGRAMA_EMP_TBL_CATEGORIA FOREIGN KEY (CEA_CATEGORIA) REFERENCES TBL_CATEGORIA(CDA_CATEGORIA)
		ON DELETE CASCADE
go

ALTER TABLE TBL_TURMA_EMP
	ADD CONSTRAINT  FK_TBL_PROGRAMA_EMP_TBL_FATURAMENTO FOREIGN KEY (CEA_FATURAMENTO) REFERENCES TBL_FATURAMENTO(CDA_FATURAMENTO)
		ON DELETE CASCADE
go

ALTER TABLE TBL_TURMA_EMP
	ADD CONSTRAINT  FK_TBL_PROGRAMA_EMP_TBL_RAMO_ATIVIDADE FOREIGN KEY (CEA_ATIVIDADE_ECONOMICA) REFERENCES TBL_ATIVIDADE_ECONOMICA(CDA_ATIVIDADE_ECONOMICA)
		ON DELETE CASCADE
go

ALTER TABLE TBL_TURMA_EMP
	ADD CONSTRAINT  FK_TBL_REL_EMP_PROGRAMA_TBL_EMP_CADASTRO FOREIGN KEY (CEA_EMP_CADASTRO) REFERENCES TBL_EMP_CADASTRO(CDA_EMP_CADASTRO)
		ON DELETE CASCADE
go

ALTER TABLE TBL_TURMA_EMP
	ADD CONSTRAINT  FK_TBL_REL_PROGRAMA_EMP_TBL_ESTADO FOREIGN KEY (CEA_ESTADO) REFERENCES TBL_ESTADO(CDA_ESTADO)
		ON DELETE CASCADE
go

ALTER TABLE TBL_TURMA_EMP
	ADD CONSTRAINT  FK_TBL_REL_PROGRAMA_EMP_TBL_PAIS FOREIGN KEY (CEA_PAIS) REFERENCES TBL_PAIS(CDA_PAIS)
		ON DELETE CASCADE
go

ALTER TABLE TBL_TURMA_EMP
	ADD CONSTRAINT  R_107 FOREIGN KEY (CEA_NIVEL_ESCOLARIDADE) REFERENCES TBL_CONTATO_NIVEL_ESCOLARIDADE(CDA_NIVEL_ESCOLARIDADE)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go

ALTER TABLE TBL_TURMA_EMP
	ADD CONSTRAINT  R_108 FOREIGN KEY (CEA_FAIXA_ETARIA) REFERENCES TBL_CONTATO_FAIXA_ETARIA(CDA_FAIXA_ETARIA)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go

ALTER TABLE TBL_TURMA_EMP
	ADD CONSTRAINT  R_109 FOREIGN KEY (CEA_CIDADE) REFERENCES TBL_CIDADE(CDA_CIDADE)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go

ALTER TABLE TBL_TURMA_EMP
	ADD CONSTRAINT  R_121 FOREIGN KEY (CEA_TURMA) REFERENCES TBL_TURMA(CDA_TURMA)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go

ALTER TABLE TBL_TURMA_EMP
	ADD CONSTRAINT  R_153 FOREIGN KEY (CEA_TIPO_EMPRESA) REFERENCES TBL_TIPO_EMP(CDA_TIPO_EMPRESA)
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go

